import Foundation

struct LocalizationCatalog: Sendable {
    static let `default` = LocalizationCatalog(translations: defaultTranslations)

    private let translations: [AppLanguage: [LocalizationKey: String]]

    init(translations: [AppLanguage: [LocalizationKey: String]]) {
        self.translations = translations
    }

    func localizedString(for key: LocalizationKey, language: AppLanguage) -> String {
        if let value = translations[language]?[key] {
            return value
        }

        if let fallback = translations[.english]?[key] {
            #if DEBUG
            AppLog.app.warning("Missing localization key \(key.rawValue, privacy: .public) for \(language.rawValue, privacy: .public)")
            #endif
            return fallback
        }

        #if DEBUG
        AppLog.app.warning("Missing English localization key \(key.rawValue, privacy: .public)")
        #endif
        return key.rawValue
    }

    func hasTranslation(for key: LocalizationKey, language: AppLanguage) -> Bool {
        translations[language]?[key] != nil
    }

    // Dictionaries follow the LocalizationKey declaration order; the completeness
    // test fails the build when any language misses any key.
    private static let defaultTranslations: [AppLanguage: [LocalizationKey: String]] = [
        .english: [
            .aboutAccessibilityLabel: "Accessibility",
            .aboutDescriptionPrivacy: "Layouts stay on this Mac. Perch reads windows when saving and moves them for manual restores or when automatic restore is enabled.",
            .aboutDescriptionRestore: "Create named layouts for work, focus, meetings, or anything else. Restore them from the menu bar or with keyboard shortcuts, even across multiple displays.",
            .aboutDescriptionSummary: "Perch is a quiet menu bar app for saving your Mac window setup and restoring it when you need the same workspace again.",
            .aboutDiagnosticsRedacted: "Diagnostics are redacted, not anonymous. They include app and layout identifiers, display geometry, counts, timestamps, settings, and system details. Window titles and layout names are excluded.",
            .aboutExportDiagnostics: "Export Diagnostics…",
            .aboutGranted: "Granted",
            .aboutMadeBy: "Made by Code&live",
            .aboutMissing: "Missing",
            .aboutTabTitle: "About",
            .aboutVersionFormat: "Version %@",
            .accessibilityBannerPendingMessage: "If Perch is already enabled in System Settings, restart it so macOS attaches the permission to the running app.",
            .accessibilityBannerPendingTitle: "Accessibility permission pending",
            .accessibilityBannerRequiredMessage: "Perch needs Accessibility access to read and move windows.",
            .accessibilityBannerRequiredTitle: "Accessibility permission required",
            .accessibilityGranted: "Accessibility permission granted",
            .accessibilityPermissionPending: "Accessibility permission pending. Restart Perch if it is already enabled.",
            .accessibilityPermissionResetEnable: "Accessibility permission reset. Enable Perch in System Settings.",
            .addButton: "Add",
            .allWindowsRestored: "All windows restored",
            .appLabel: "App",
            .applicationClosed: "Application is closed.",
            .applicationNotInstalled: "Application is not installed.",
            .autoRestoreAdvanced: "Advanced",
            .autoRestoreAutomatic: "Restore automatically",
            .autoRestoreDecisionAlreadyOffered: "suggestion already shown",
            .autoRestoreDecisionDisabled: "disabled",
            .autoRestoreDecisionEmptyLayout: "matching layout is empty",
            .autoRestoreDecisionError: "decision failed",
            .autoRestoreDecisionNoLayout: "no layout for this arrangement",
            .autoRestoreDecisionPromptFormat: "offered %@",
            .autoRestoreDecisionRestoreFormat: "started automatic restore for %@",
            .autoRestoreDecisionTopologyIncomplete: "display arrangement is still incomplete",
            .autoRestoreDecisionTopologyUnchanged: "display arrangement unchanged",
            .autoRestoreDoNothing: "Do nothing",
            .autoRestoreModeLabel: "When displays change",
            .autoRestorePrompt: "Ask me",
            .autoRestorePromptFooter: "Perch will offer to restore the layout saved for this display arrangement.",
            .autoRestoreSectionTitle: "Automatic restore",
            .autoRestoreSettleTimeoutFooter: "How long Perch waits for a dock or displays to finish connecting before checking the arrangement.",
            .autoRestoreSettleTimeoutLabel: "Display settle timeout",
            .automaticUpdateChecksToggle: "Automatically check for updates",
            .bundleIDLabel: "Bundle ID",
            .cancelButton: "Cancel",
            .checkForUpdatesMenuItem: "Check for Updates…",
            .chooseLayoutName: "Choose a name for this layout.",
            .clearCustomShortcutHelp: "Clear custom shortcut",
            .createLayout: "Create Layout",
            .createdLayoutFormat: "Created %@",
            .deleteButton: "Delete",
            .deleteLayoutHelp: "Delete layout",
            .deleteLayoutMessageFormat: "“%@” and its saved windows will be removed.",
            .deleteLayoutTitle: "Delete layout?",
            .diagnosticsExported: "Diagnostics exported",
            .errorSectionTitle: "Error",
            .generalTabTitle: "General",
            .grantAccessibilityPermission: "Grant Accessibility Permission…",
            .grantAccessibilityPermissionPending: "Accessibility Permission Pending…",
            .hotkeyActionRestoreFormat: "restore %@",
            .hotkeyActionSaveFormat: "save %@",
            .hotkeyRecordPrompt: "Click here, then press a shortcut",
            .hotkeyRequiresModifier: "Use at least one modifier",
            .languagePickerLabel: "Language",
            .languageSectionTitle: "Language",
            .lastAutomaticDecisionFormat: "Automatic restore: %@",
            .lastRestoreReport: "Last Restore Report",
            .launchAtLogin: "Launch at login",
            .launchAtLoginStatus: "Login item status",
            .launchDidNotReturnApp: "macOS did not return a running application.",
            .launchStatusDisabled: "Disabled",
            .launchStatusEnabled: "Enabled",
            .launchStatusRequiresApproval: "Requires approval in System Settings",
            .launchStatusUnavailable: "Unavailable",
            .launchStatusUnknown: "Unknown",
            .layoutNameCannotBeEmpty: "Layout name cannot be empty.",
            .layoutNameField: "Layout name",
            .layoutNotFoundFormat: "Layout not found: %@",
            .layoutsSectionTitle: "Layouts",
            .layoutsTabTitle: "Layouts",
            .matchReasonOnlyOpenWindow: "only open window for this app",
            .matchReasonSameLiveWindow: "same live window",
            .matchReasonSavedWindowIdentity: "saved window identity",
            .matchReasonWindowTitle: "window title",
            .matchedByLabel: "Matched by",
            .menuBarFooter: "When off, only the Perch icon is shown in the menu bar.",
            .menuBarSectionTitle: "Menu bar",
            .menuBarShowLabel: "Show label next to menu bar icon",
            .menuOutcomeAmbiguousWindows: "ambiguous windows",
            .menuOutcomeClosed: "closed",
            .menuOutcomeLaunchFailed: "launch failed",
            .menuOutcomeMoveFailed: "move failed",
            .menuOutcomeNotInstalled: "not installed",
            .menuOutcomeOpenedAndRestored: "opened and restored",
            .menuOutcomeRestored: "restored",
            .menuOutcomeSkipped: "skipped",
            .menuOutcomeWindowNotFound: "window not found",
            .newLayoutDefaultName: "New Layout",
            .newLayoutNamePlaceholder: "New layout name",
            .noLayouts: "No layouts yet.",
            .noLayoutsYet: "No layouts yet",
            .noRestoreShortcut: "No restore shortcut",
            .noWindowsSaved: "No windows saved",
            .noWindowsSavedYet: "No windows saved yet",
            .openMissingAppsDuringRestore: "Open missing apps during restore",
            .openSystemSettings: "Open System Settings",
            .openedDuringRestore: "Perch opened this app during restore.",
            .operationAlreadyRunning: "Another save or restore is already running.",
            .quitPerch: "Quit Perch",
            .reasonLabel: "Reason",
            .recordRestoreShortcutHelp: "Record restore shortcut",
            .refreshButton: "Refresh",
            .resetAccessibilityPermission: "Reset Accessibility Permission…",
            .resetPermissionButton: "Reset Permission",
            .restartPerch: "Restart Perch",
            .restoreLayoutFormat: "Restore %@",
            .restorePromptButton: "Restore",
            .restorePromptDismiss: "Dismiss restore suggestion",
            .restorePromptShortcutFormat: "Press %@ to restore",
            .restorePromptTitleFormat: "Restore %@?",
            .restoreSectionFooter: "When off, closed apps stay closed and only currently open windows are moved.",
            .restoreSectionTitle: "Restore",
            .saveButton: "Save",
            .saveCurrentWindowsFormat: "Save Current Windows to “%@”",
            .settingsMenuItem: "Settings…",
            .settingsWindowTitle: "Perch Settings",
            .shortcutAlreadyUsedRestoreFormat: "Shortcut is already used to restore %@.",
            .shortcutAlreadyUsedSaveFormat: "Shortcut is already used to save %@.",
            .shortcutRejectedTooltipFormat: "macOS rejected this shortcut with status %d. It may already be used by the system or another app.",
            .shortcutUnavailableTooltipFormat: "Shortcut %@ could not be registered. macOS or another app may already use it.",
            .slotNotFoundFormat: "Slot not found: %@",
            .someShortcutsUnavailable: "Some Shortcuts Are Unavailable",
            .startupSectionTitle: "Startup",
            .updateLayoutWindowsFormat: "Update “%@” with Current Windows",
            .updatesSectionTitle: "Updates",
            .windowLabel: "Window",
            .windowsAndShortcutFormat: "%d %@ · %@"
        ],
        .czech: [
            .aboutAccessibilityLabel: "Zpřístupnění",
            .aboutDescriptionPrivacy: "Rozložení zůstávají na tomto Macu. Perch čte okna při ukládání a přesouvá je při ručním obnovení nebo když je zapnuté automatické obnovení.",
            .aboutDescriptionRestore: "Vytvářejte pojmenovaná rozložení pro práci, soustředění, schůzky nebo cokoliv dalšího. Obnovíte je z lišty nebo klávesovou zkratkou, i přes více displejů.",
            .aboutDescriptionSummary: "Perch je nenápadná aplikace v liště pro ukládání rozložení oken na Macu a jeho obnovení, když znovu potřebujete stejný pracovní prostor.",
            .aboutDiagnosticsRedacted: "Diagnostika je redigovaná, nikoli anonymní. Obsahuje identifikátory aplikací a rozložení, geometrii displejů, počty, časové údaje, nastavení a údaje o systému. Názvy oken a rozložení se neexportují.",
            .aboutExportDiagnostics: "Exportovat diagnostiku…",
            .aboutGranted: "Povoleno",
            .aboutMadeBy: "Vytvořilo Code&live",
            .aboutMissing: "Chybí",
            .aboutTabTitle: "O aplikaci",
            .aboutVersionFormat: "Verze %@",
            .accessibilityBannerPendingMessage: "Pokud už je Perch v Nastavení systému povolený, restartujte ho, aby macOS oprávnění připojil k běžící aplikaci.",
            .accessibilityBannerPendingTitle: "Oprávnění Zpřístupnění čeká",
            .accessibilityBannerRequiredMessage: "Perch potřebuje přístup ke Zpřístupnění, aby mohl číst a přesouvat okna.",
            .accessibilityBannerRequiredTitle: "Je vyžadováno oprávnění Zpřístupnění",
            .accessibilityGranted: "Oprávnění Zpřístupnění povoleno",
            .accessibilityPermissionPending: "Oprávnění Zpřístupnění čeká. Pokud už je Perch povolený, restartujte ho.",
            .accessibilityPermissionResetEnable: "Oprávnění Zpřístupnění resetováno. Povolte Perch v Nastavení systému.",
            .addButton: "Přidat",
            .allWindowsRestored: "Všechna okna obnovena",
            .appLabel: "Aplikace",
            .applicationClosed: "Aplikace je zavřená.",
            .applicationNotInstalled: "Aplikace není nainstalovaná.",
            .autoRestoreAdvanced: "Pokročilé",
            .autoRestoreAutomatic: "Obnovit automaticky",
            .autoRestoreDecisionAlreadyOffered: "nabídka už byla zobrazena",
            .autoRestoreDecisionDisabled: "vypnuto",
            .autoRestoreDecisionEmptyLayout: "odpovídající rozložení je prázdné",
            .autoRestoreDecisionError: "rozhodnutí selhalo",
            .autoRestoreDecisionNoLayout: "pro tuto sestavu není rozložení",
            .autoRestoreDecisionPromptFormat: "nabídnuto %@",
            .autoRestoreDecisionRestoreFormat: "zahájena automatická obnova: %@",
            .autoRestoreDecisionTopologyIncomplete: "sestava displejů ještě není kompletní",
            .autoRestoreDecisionTopologyUnchanged: "sestava displejů se nezměnila",
            .autoRestoreDoNothing: "Nedělat nic",
            .autoRestoreModeLabel: "Při změně displejů",
            .autoRestorePrompt: "Zeptat se",
            .autoRestorePromptFooter: "Perch nabídne obnovení rozložení uloženého pro tuto sestavu displejů.",
            .autoRestoreSectionTitle: "Automatické obnovení",
            .autoRestoreSettleTimeoutFooter: "Jak dlouho Perch čeká, než se dok nebo displeje dokončí připojování, a teprve potom zkontroluje sestavu.",
            .autoRestoreSettleTimeoutLabel: "Čas na ustálení displejů",
            .automaticUpdateChecksToggle: "Automaticky kontrolovat aktualizace",
            .bundleIDLabel: "Bundle ID",
            .cancelButton: "Zrušit",
            .checkForUpdatesMenuItem: "Zkontrolovat aktualizace…",
            .chooseLayoutName: "Zvolte název tohoto rozložení.",
            .clearCustomShortcutHelp: "Vymazat vlastní zkratku",
            .createLayout: "Vytvořit rozložení",
            .createdLayoutFormat: "Vytvořeno %@",
            .deleteButton: "Smazat",
            .deleteLayoutHelp: "Smazat rozložení",
            .deleteLayoutMessageFormat: "„%@“ a jeho uložená okna budou odstraněna.",
            .deleteLayoutTitle: "Smazat rozložení?",
            .diagnosticsExported: "Diagnostika exportována",
            .errorSectionTitle: "Chyba",
            .generalTabTitle: "Obecné",
            .grantAccessibilityPermission: "Udělit oprávnění Zpřístupnění…",
            .grantAccessibilityPermissionPending: "Oprávnění Zpřístupnění čeká…",
            .hotkeyActionRestoreFormat: "obnovit %@",
            .hotkeyActionSaveFormat: "uložit %@",
            .hotkeyRecordPrompt: "Klikněte sem a stiskněte zkratku",
            .hotkeyRequiresModifier: "Použijte alespoň jeden modifikátor",
            .languagePickerLabel: "Jazyk",
            .languageSectionTitle: "Jazyk",
            .lastAutomaticDecisionFormat: "Automatické obnovení: %@",
            .lastRestoreReport: "Poslední hlášení obnovení",
            .launchAtLogin: "Spustit po přihlášení",
            .launchAtLoginStatus: "Stav položky přihlášení",
            .launchDidNotReturnApp: "macOS nevrátil běžící aplikaci.",
            .launchStatusDisabled: "Vypnuto",
            .launchStatusEnabled: "Zapnuto",
            .launchStatusRequiresApproval: "Vyžaduje schválení v Nastavení systému",
            .launchStatusUnavailable: "Nedostupné",
            .launchStatusUnknown: "Neznámé",
            .layoutNameCannotBeEmpty: "Název rozložení nesmí být prázdný.",
            .layoutNameField: "Název rozložení",
            .layoutNotFoundFormat: "Rozložení nenalezeno: %@",
            .layoutsSectionTitle: "Rozložení",
            .layoutsTabTitle: "Rozložení",
            .matchReasonOnlyOpenWindow: "jediné otevřené okno této aplikace",
            .matchReasonSameLiveWindow: "stejné živé okno",
            .matchReasonSavedWindowIdentity: "uložená identita okna",
            .matchReasonWindowTitle: "titulek okna",
            .matchedByLabel: "Shoda podle",
            .menuBarFooter: "Když je volba vypnutá, v liště se zobrazí jen ikona Perch.",
            .menuBarSectionTitle: "Lišta nabídek",
            .menuBarShowLabel: "Zobrazit popisek vedle ikony v liště",
            .menuOutcomeAmbiguousWindows: "nejednoznačná okna",
            .menuOutcomeClosed: "zavřeno",
            .menuOutcomeLaunchFailed: "spuštění selhalo",
            .menuOutcomeMoveFailed: "přesun selhal",
            .menuOutcomeNotInstalled: "není nainstalováno",
            .menuOutcomeOpenedAndRestored: "otevřeno a obnoveno",
            .menuOutcomeRestored: "obnoveno",
            .menuOutcomeSkipped: "přeskočeno",
            .menuOutcomeWindowNotFound: "okno nenalezeno",
            .newLayoutDefaultName: "Nové rozložení",
            .newLayoutNamePlaceholder: "Název nového rozložení",
            .noLayouts: "Zatím žádná rozložení.",
            .noLayoutsYet: "Zatím žádná rozložení",
            .noRestoreShortcut: "Žádná zkratka pro obnovení",
            .noWindowsSaved: "Nejsou uložena žádná okna",
            .noWindowsSavedYet: "Zatím nejsou uložena žádná okna",
            .openMissingAppsDuringRestore: "Při obnovení otevřít chybějící aplikace",
            .openSystemSettings: "Otevřít Nastavení systému",
            .openedDuringRestore: "Perch tuto aplikaci během obnovení otevřel.",
            .operationAlreadyRunning: "Jiné ukládání nebo obnovování právě běží.",
            .quitPerch: "Ukončit Perch",
            .reasonLabel: "Důvod",
            .recordRestoreShortcutHelp: "Nahrát zkratku pro obnovení",
            .refreshButton: "Obnovit",
            .resetAccessibilityPermission: "Resetovat oprávnění Zpřístupnění…",
            .resetPermissionButton: "Resetovat oprávnění",
            .restartPerch: "Restartovat Perch",
            .restoreLayoutFormat: "Obnovit %@",
            .restorePromptButton: "Obnovit",
            .restorePromptDismiss: "Zavřít nabídku obnovení",
            .restorePromptShortcutFormat: "Obnovíte stisknutím %@",
            .restorePromptTitleFormat: "Obnovit %@?",
            .restoreSectionFooter: "Když je volba vypnutá, zavřené aplikace zůstanou zavřené a přesunou se jen právě otevřená okna.",
            .restoreSectionTitle: "Obnovení",
            .saveButton: "Uložit",
            .saveCurrentWindowsFormat: "Uložit aktuální okna do „%@“",
            .settingsMenuItem: "Nastavení…",
            .settingsWindowTitle: "Nastavení Perch",
            .shortcutAlreadyUsedRestoreFormat: "Zkratka se už používá pro obnovení %@.",
            .shortcutAlreadyUsedSaveFormat: "Zkratka se už používá pro uložení %@.",
            .shortcutRejectedTooltipFormat: "macOS odmítl tuto zkratku se stavem %d. Možná ji už používá systém nebo jiná aplikace.",
            .shortcutUnavailableTooltipFormat: "Zkratku %@ se nepodařilo zaregistrovat. Možná ji už používá macOS nebo jiná aplikace.",
            .slotNotFoundFormat: "Slot nenalezen: %@",
            .someShortcutsUnavailable: "Některé zkratky nejsou dostupné",
            .startupSectionTitle: "Spuštění",
            .updateLayoutWindowsFormat: "Aktualizovat „%@“ aktuálními okny",
            .updatesSectionTitle: "Aktualizace",
            .windowLabel: "Okno",
            .windowsAndShortcutFormat: "%d %@ · %@"
        ],
        .slovak: [
            .aboutAccessibilityLabel: "Prístupnosť",
            .aboutDescriptionPrivacy: "Rozloženia zostávajú na tomto Macu. Perch číta okná pri ukladaní a presúva ich pri ručnom obnovení alebo keď je zapnuté automatické obnovenie.",
            .aboutDescriptionRestore: "Vytvárajte pomenované rozloženia pre prácu, sústredenie, schôdzky alebo čokoľvek ďalšie. Obnovíte ich z lišty alebo klávesovou skratkou, aj cez viac displejov.",
            .aboutDescriptionSummary: "Perch je nenápadná aplikácia v lište na ukladanie rozloženia okien na Macu a jeho obnovenie, keď znova potrebujete rovnaký pracovný priestor.",
            .aboutDiagnosticsRedacted: "Diagnostika je redigovaná, nie anonymná. Obsahuje identifikátory aplikácií a rozložení, geometriu displejov, počty, časové údaje, nastavenia a údaje o systéme. Názvy okien a rozložení sa neexportujú.",
            .aboutExportDiagnostics: "Exportovať diagnostiku…",
            .aboutGranted: "Povolené",
            .aboutMadeBy: "Vytvorilo Code&live",
            .aboutMissing: "Chýba",
            .aboutTabTitle: "O aplikácii",
            .aboutVersionFormat: "Verzia %@",
            .accessibilityBannerPendingMessage: "Ak je Perch už povolený v Nastaveniach systému, reštartujte ho, aby macOS pripojil oprávnenie k bežiacej aplikácii.",
            .accessibilityBannerPendingTitle: "Oprávnenie Prístupnosť čaká",
            .accessibilityBannerRequiredMessage: "Perch potrebuje prístup k Prístupnosti, aby mohol čítať a presúvať okná.",
            .accessibilityBannerRequiredTitle: "Vyžaduje sa oprávnenie Prístupnosť",
            .accessibilityGranted: "Oprávnenie Prístupnosť povolené",
            .accessibilityPermissionPending: "Oprávnenie Prístupnosť čaká. Ak je Perch už povolený, reštartujte ho.",
            .accessibilityPermissionResetEnable: "Oprávnenie Prístupnosť resetované. Povoľte Perch v Nastaveniach systému.",
            .addButton: "Pridať",
            .allWindowsRestored: "Všetky okná obnovené",
            .appLabel: "Aplikácia",
            .applicationClosed: "Aplikácia je zatvorená.",
            .applicationNotInstalled: "Aplikácia nie je nainštalovaná.",
            .autoRestoreAdvanced: "Pokročilé",
            .autoRestoreAutomatic: "Obnoviť automaticky",
            .autoRestoreDecisionAlreadyOffered: "ponuka už bola zobrazená",
            .autoRestoreDecisionDisabled: "vypnuté",
            .autoRestoreDecisionEmptyLayout: "zodpovedajúce rozloženie je prázdne",
            .autoRestoreDecisionError: "rozhodnutie zlyhalo",
            .autoRestoreDecisionNoLayout: "pre túto zostavu nie je rozloženie",
            .autoRestoreDecisionPromptFormat: "ponúknuté %@",
            .autoRestoreDecisionRestoreFormat: "spustené automatické obnovenie: %@",
            .autoRestoreDecisionTopologyIncomplete: "zostava displejov ešte nie je kompletná",
            .autoRestoreDecisionTopologyUnchanged: "zostava displejov sa nezmenila",
            .autoRestoreDoNothing: "Nerobiť nič",
            .autoRestoreModeLabel: "Pri zmene displejov",
            .autoRestorePrompt: "Opýtať sa",
            .autoRestorePromptFooter: "Perch ponúkne obnovenie rozloženia uloženého pre túto zostavu displejov.",
            .autoRestoreSectionTitle: "Automatické obnovenie",
            .autoRestoreSettleTimeoutFooter: "Ako dlho Perch čaká, kým sa dok alebo displeje dokončia pripájať, a až potom skontroluje zostavu.",
            .autoRestoreSettleTimeoutLabel: "Čas na ustálenie displejov",
            .automaticUpdateChecksToggle: "Automaticky kontrolovať aktualizácie",
            .bundleIDLabel: "Bundle ID",
            .cancelButton: "Zrušiť",
            .checkForUpdatesMenuItem: "Skontrolovať aktualizácie…",
            .chooseLayoutName: "Zvoľte názov tohto rozloženia.",
            .clearCustomShortcutHelp: "Vymazať vlastnú skratku",
            .createLayout: "Vytvoriť rozloženie",
            .createdLayoutFormat: "Vytvorené %@",
            .deleteButton: "Vymazať",
            .deleteLayoutHelp: "Vymazať rozloženie",
            .deleteLayoutMessageFormat: "„%@“ a jeho uložené okná budú odstránené.",
            .deleteLayoutTitle: "Vymazať rozloženie?",
            .diagnosticsExported: "Diagnostika exportovaná",
            .errorSectionTitle: "Chyba",
            .generalTabTitle: "Všeobecné",
            .grantAccessibilityPermission: "Udeliť oprávnenie Prístupnosť…",
            .grantAccessibilityPermissionPending: "Oprávnenie Prístupnosť čaká…",
            .hotkeyActionRestoreFormat: "obnoviť %@",
            .hotkeyActionSaveFormat: "uložiť %@",
            .hotkeyRecordPrompt: "Kliknite sem a stlačte skratku",
            .hotkeyRequiresModifier: "Použite aspoň jeden modifikátor",
            .languagePickerLabel: "Jazyk",
            .languageSectionTitle: "Jazyk",
            .lastAutomaticDecisionFormat: "Automatické obnovenie: %@",
            .lastRestoreReport: "Posledné hlásenie obnovenia",
            .launchAtLogin: "Spustiť po prihlásení",
            .launchAtLoginStatus: "Stav položky prihlásenia",
            .launchDidNotReturnApp: "macOS nevrátil bežiacu aplikáciu.",
            .launchStatusDisabled: "Vypnuté",
            .launchStatusEnabled: "Zapnuté",
            .launchStatusRequiresApproval: "Vyžaduje schválenie v Nastaveniach systému",
            .launchStatusUnavailable: "Nedostupné",
            .launchStatusUnknown: "Neznáme",
            .layoutNameCannotBeEmpty: "Názov rozloženia nesmie byť prázdny.",
            .layoutNameField: "Názov rozloženia",
            .layoutNotFoundFormat: "Rozloženie nenájdené: %@",
            .layoutsSectionTitle: "Rozloženia",
            .layoutsTabTitle: "Rozloženia",
            .matchReasonOnlyOpenWindow: "jediné otvorené okno tejto aplikácie",
            .matchReasonSameLiveWindow: "rovnaké živé okno",
            .matchReasonSavedWindowIdentity: "uložená identita okna",
            .matchReasonWindowTitle: "titulok okna",
            .matchedByLabel: "Zhoda podľa",
            .menuBarFooter: "Keď je voľba vypnutá, v lište sa zobrazí iba ikona Perch.",
            .menuBarSectionTitle: "Lišta menu",
            .menuBarShowLabel: "Zobraziť popis vedľa ikony v lište",
            .menuOutcomeAmbiguousWindows: "nejednoznačné okná",
            .menuOutcomeClosed: "zatvorené",
            .menuOutcomeLaunchFailed: "spustenie zlyhalo",
            .menuOutcomeMoveFailed: "presun zlyhal",
            .menuOutcomeNotInstalled: "nie je nainštalované",
            .menuOutcomeOpenedAndRestored: "otvorené a obnovené",
            .menuOutcomeRestored: "obnovené",
            .menuOutcomeSkipped: "preskočené",
            .menuOutcomeWindowNotFound: "okno nenájdené",
            .newLayoutDefaultName: "Nové rozloženie",
            .newLayoutNamePlaceholder: "Názov nového rozloženia",
            .noLayouts: "Zatiaľ žiadne rozloženia.",
            .noLayoutsYet: "Zatiaľ žiadne rozloženia",
            .noRestoreShortcut: "Žiadna skratka pre obnovenie",
            .noWindowsSaved: "Nie sú uložené žiadne okná",
            .noWindowsSavedYet: "Zatiaľ nie sú uložené žiadne okná",
            .openMissingAppsDuringRestore: "Pri obnovení otvoriť chýbajúce aplikácie",
            .openSystemSettings: "Otvoriť Nastavenia systému",
            .openedDuringRestore: "Perch túto aplikáciu počas obnovenia otvoril.",
            .operationAlreadyRunning: "Iné ukladanie alebo obnovovanie práve beží.",
            .quitPerch: "Ukončiť Perch",
            .reasonLabel: "Dôvod",
            .recordRestoreShortcutHelp: "Nahrať skratku pre obnovenie",
            .refreshButton: "Obnoviť",
            .resetAccessibilityPermission: "Resetovať oprávnenie Prístupnosť…",
            .resetPermissionButton: "Resetovať oprávnenie",
            .restartPerch: "Reštartovať Perch",
            .restoreLayoutFormat: "Obnoviť %@",
            .restorePromptButton: "Obnoviť",
            .restorePromptDismiss: "Zavrieť ponuku obnovenia",
            .restorePromptShortcutFormat: "Obnovíte stlačením %@",
            .restorePromptTitleFormat: "Obnoviť %@?",
            .restoreSectionFooter: "Keď je voľba vypnutá, zatvorené aplikácie zostanú zatvorené a presunú sa iba aktuálne otvorené okná.",
            .restoreSectionTitle: "Obnovenie",
            .saveButton: "Uložiť",
            .saveCurrentWindowsFormat: "Uložiť aktuálne okná do „%@“",
            .settingsMenuItem: "Nastavenia…",
            .settingsWindowTitle: "Nastavenia Perch",
            .shortcutAlreadyUsedRestoreFormat: "Skratka sa už používa na obnovenie %@.",
            .shortcutAlreadyUsedSaveFormat: "Skratka sa už používa na uloženie %@.",
            .shortcutRejectedTooltipFormat: "macOS odmietol túto skratku so stavom %d. Možno ju už používa systém alebo iná aplikácia.",
            .shortcutUnavailableTooltipFormat: "Skratku %@ sa nepodarilo zaregistrovať. Možno ju už používa macOS alebo iná aplikácia.",
            .slotNotFoundFormat: "Slot nenájdený: %@",
            .someShortcutsUnavailable: "Niektoré skratky nie sú dostupné",
            .startupSectionTitle: "Spustenie",
            .updateLayoutWindowsFormat: "Aktualizovať „%@“ aktuálnymi oknami",
            .updatesSectionTitle: "Aktualizácie",
            .windowLabel: "Okno",
            .windowsAndShortcutFormat: "%d %@ · %@"
        ],
        .spanish: [
            .aboutAccessibilityLabel: "Accesibilidad",
            .aboutDescriptionPrivacy: "Los diseños permanecen en este Mac. Perch lee las ventanas al guardar y las mueve en restauraciones manuales o cuando está activada la restauración automática.",
            .aboutDescriptionRestore: "Crea diseños con nombre para trabajo, concentración, reuniones o cualquier otra cosa. Restáuralos desde la barra de menús o con atajos de teclado, incluso en varios monitores.",
            .aboutDescriptionSummary: "Perch es una app discreta de barra de menús para guardar la disposición de ventanas de tu Mac y restaurarla cuando necesites el mismo espacio de trabajo.",
            .aboutDiagnosticsRedacted: "El diagnóstico está redactado, no es anónimo. Incluye identificadores de apps y diseños, geometría de pantallas, recuentos, fechas, ajustes y datos del sistema. Excluye títulos de ventanas y nombres de diseños.",
            .aboutExportDiagnostics: "Exportar diagnóstico…",
            .aboutGranted: "Concedido",
            .aboutMadeBy: "Hecho por Code&live",
            .aboutMissing: "Falta",
            .aboutTabTitle: "Acerca de",
            .aboutVersionFormat: "Versión %@",
            .accessibilityBannerPendingMessage: "Si Perch ya está permitido en Ajustes del Sistema, reinícialo para que macOS asocie el permiso a la app en ejecución.",
            .accessibilityBannerPendingTitle: "Permiso de Accesibilidad pendiente",
            .accessibilityBannerRequiredMessage: "Perch necesita acceso de Accesibilidad para leer y mover ventanas.",
            .accessibilityBannerRequiredTitle: "Se requiere permiso de Accesibilidad",
            .accessibilityGranted: "Permiso de Accesibilidad concedido",
            .accessibilityPermissionPending: "Permiso de Accesibilidad pendiente. Reinicia Perch si ya está permitido.",
            .accessibilityPermissionResetEnable: "Permiso de Accesibilidad restablecido. Permite Perch en Ajustes del Sistema.",
            .addButton: "Añadir",
            .allWindowsRestored: "Todas las ventanas restauradas",
            .appLabel: "App",
            .applicationClosed: "La aplicación está cerrada.",
            .applicationNotInstalled: "La aplicación no está instalada.",
            .autoRestoreAdvanced: "Avanzado",
            .autoRestoreAutomatic: "Restaurar automáticamente",
            .autoRestoreDecisionAlreadyOffered: "sugerencia ya mostrada",
            .autoRestoreDecisionDisabled: "desactivado",
            .autoRestoreDecisionEmptyLayout: "el diseño coincidente está vacío",
            .autoRestoreDecisionError: "falló la decisión",
            .autoRestoreDecisionNoLayout: "no hay diseño para esta configuración",
            .autoRestoreDecisionPromptFormat: "se ofreció %@",
            .autoRestoreDecisionRestoreFormat: "restauración automática iniciada: %@",
            .autoRestoreDecisionTopologyIncomplete: "la configuración de pantallas aún está incompleta",
            .autoRestoreDecisionTopologyUnchanged: "la configuración de pantallas no cambió",
            .autoRestoreDoNothing: "No hacer nada",
            .autoRestoreModeLabel: "Cuando cambien las pantallas",
            .autoRestorePrompt: "Preguntarme",
            .autoRestorePromptFooter: "Perch ofrecerá restaurar el diseño guardado para esta configuración de pantallas.",
            .autoRestoreSectionTitle: "Restauración automática",
            .autoRestoreSettleTimeoutFooter: "Cuánto espera Perch a que el dock o las pantallas terminen de conectarse antes de comprobar la configuración.",
            .autoRestoreSettleTimeoutLabel: "Espera de estabilización",
            .automaticUpdateChecksToggle: "Buscar actualizaciones automáticamente",
            .bundleIDLabel: "Bundle ID",
            .cancelButton: "Cancelar",
            .checkForUpdatesMenuItem: "Buscar actualizaciones…",
            .chooseLayoutName: "Elige un nombre para este diseño.",
            .clearCustomShortcutHelp: "Borrar atajo personalizado",
            .createLayout: "Crear diseño",
            .createdLayoutFormat: "%@ creado",
            .deleteButton: "Eliminar",
            .deleteLayoutHelp: "Eliminar diseño",
            .deleteLayoutMessageFormat: "“%@” y sus ventanas guardadas se eliminarán.",
            .deleteLayoutTitle: "¿Eliminar diseño?",
            .diagnosticsExported: "Diagnóstico exportado",
            .errorSectionTitle: "Error",
            .generalTabTitle: "General",
            .grantAccessibilityPermission: "Conceder permiso de Accesibilidad…",
            .grantAccessibilityPermissionPending: "Permiso de Accesibilidad pendiente…",
            .hotkeyActionRestoreFormat: "restaurar %@",
            .hotkeyActionSaveFormat: "guardar %@",
            .hotkeyRecordPrompt: "Haz clic aquí y pulsa un atajo",
            .hotkeyRequiresModifier: "Usa al menos un modificador",
            .languagePickerLabel: "Idioma",
            .languageSectionTitle: "Idioma",
            .lastAutomaticDecisionFormat: "Restauración automática: %@",
            .lastRestoreReport: "Último informe de restauración",
            .launchAtLogin: "Abrir al iniciar sesión",
            .launchAtLoginStatus: "Estado del inicio de sesión",
            .launchDidNotReturnApp: "macOS no devolvió una aplicación en ejecución.",
            .launchStatusDisabled: "Desactivado",
            .launchStatusEnabled: "Activado",
            .launchStatusRequiresApproval: "Requiere aprobación en Ajustes del Sistema",
            .launchStatusUnavailable: "No disponible",
            .launchStatusUnknown: "Desconocido",
            .layoutNameCannotBeEmpty: "El nombre del diseño no puede estar vacío.",
            .layoutNameField: "Nombre del diseño",
            .layoutNotFoundFormat: "Diseño no encontrado: %@",
            .layoutsSectionTitle: "Diseños",
            .layoutsTabTitle: "Diseños",
            .matchReasonOnlyOpenWindow: "única ventana abierta de esta app",
            .matchReasonSameLiveWindow: "misma ventana activa",
            .matchReasonSavedWindowIdentity: "identidad de ventana guardada",
            .matchReasonWindowTitle: "título de la ventana",
            .matchedByLabel: "Coincidencia por",
            .menuBarFooter: "Si está desactivado, solo se muestra el icono de Perch en la barra de menús.",
            .menuBarSectionTitle: "Barra de menús",
            .menuBarShowLabel: "Mostrar etiqueta junto al icono de la barra",
            .menuOutcomeAmbiguousWindows: "ventanas ambiguas",
            .menuOutcomeClosed: "cerrada",
            .menuOutcomeLaunchFailed: "fallo al abrir",
            .menuOutcomeMoveFailed: "fallo al mover",
            .menuOutcomeNotInstalled: "no instalada",
            .menuOutcomeOpenedAndRestored: "abierta y restaurada",
            .menuOutcomeRestored: "restaurada",
            .menuOutcomeSkipped: "omitida",
            .menuOutcomeWindowNotFound: "ventana no encontrada",
            .newLayoutDefaultName: "Nuevo diseño",
            .newLayoutNamePlaceholder: "Nombre del nuevo diseño",
            .noLayouts: "Todavía no hay diseños.",
            .noLayoutsYet: "Todavía no hay diseños",
            .noRestoreShortcut: "Sin atajo de restauración",
            .noWindowsSaved: "No hay ventanas guardadas",
            .noWindowsSavedYet: "Todavía no hay ventanas guardadas",
            .openMissingAppsDuringRestore: "Abrir apps faltantes al restaurar",
            .openSystemSettings: "Abrir Ajustes del Sistema",
            .openedDuringRestore: "Perch abrió esta app durante la restauración.",
            .operationAlreadyRunning: "Ya se está ejecutando otra operación de guardado o restauración.",
            .quitPerch: "Salir de Perch",
            .reasonLabel: "Motivo",
            .recordRestoreShortcutHelp: "Grabar atajo de restauración",
            .refreshButton: "Actualizar",
            .resetAccessibilityPermission: "Restablecer permiso de Accesibilidad…",
            .resetPermissionButton: "Restablecer permiso",
            .restartPerch: "Reiniciar Perch",
            .restoreLayoutFormat: "Restaurar %@",
            .restorePromptButton: "Restaurar",
            .restorePromptDismiss: "Cerrar sugerencia de restauración",
            .restorePromptShortcutFormat: "Pulsa %@ para restaurar",
            .restorePromptTitleFormat: "¿Restaurar %@?",
            .restoreSectionFooter: "Si está desactivado, las apps cerradas permanecen cerradas y solo se mueven las ventanas abiertas.",
            .restoreSectionTitle: "Restauración",
            .saveButton: "Guardar",
            .saveCurrentWindowsFormat: "Guardar ventanas actuales en “%@”",
            .settingsMenuItem: "Ajustes…",
            .settingsWindowTitle: "Ajustes de Perch",
            .shortcutAlreadyUsedRestoreFormat: "El atajo ya se usa para restaurar %@.",
            .shortcutAlreadyUsedSaveFormat: "El atajo ya se usa para guardar %@.",
            .shortcutRejectedTooltipFormat: "macOS rechazó este atajo con estado %d. Puede que el sistema u otra app ya lo use.",
            .shortcutUnavailableTooltipFormat: "No se pudo registrar el atajo %@. Puede que macOS u otra app ya lo use.",
            .slotNotFoundFormat: "Slot no encontrado: %@",
            .someShortcutsUnavailable: "Algunos atajos no están disponibles",
            .startupSectionTitle: "Inicio",
            .updateLayoutWindowsFormat: "Actualizar “%@” con las ventanas actuales",
            .updatesSectionTitle: "Actualizaciones",
            .windowLabel: "Ventana",
            .windowsAndShortcutFormat: "%d %@ · %@"
        ],
        .german: [
            .aboutAccessibilityLabel: "Bedienungshilfen",
            .aboutDescriptionPrivacy: "Layouts bleiben auf diesem Mac. Perch liest Fenster beim Speichern und verschiebt sie bei manuellen Wiederherstellungen oder wenn die automatische Wiederherstellung aktiviert ist.",
            .aboutDescriptionRestore: "Erstelle benannte Layouts für Arbeit, Fokus, Meetings oder anderes. Stelle sie über die Menüleiste oder Tastenkürzel wieder her, auch über mehrere Displays hinweg.",
            .aboutDescriptionSummary: "Perch ist eine ruhige Menüleisten-App zum Speichern deiner Mac-Fensteranordnung und zum Wiederherstellen desselben Arbeitsbereichs.",
            .aboutDiagnosticsRedacted: "Diagnosedaten sind redigiert, nicht anonym. Sie enthalten App- und Layout-IDs, Displaygeometrie, Anzahlen, Zeitangaben, Einstellungen und Systemdaten. Fenstertitel und Layoutnamen sind ausgeschlossen.",
            .aboutExportDiagnostics: "Diagnose exportieren…",
            .aboutGranted: "Gewährt",
            .aboutMadeBy: "Erstellt von Code&live",
            .aboutMissing: "Fehlt",
            .aboutTabTitle: "Info",
            .aboutVersionFormat: "Version %@",
            .accessibilityBannerPendingMessage: "Wenn Perch in den Systemeinstellungen bereits erlaubt ist, starte es neu, damit macOS die Berechtigung der laufenden App zuordnet.",
            .accessibilityBannerPendingTitle: "Bedienungshilfen-Berechtigung ausstehend",
            .accessibilityBannerRequiredMessage: "Perch benötigt Zugriff auf Bedienungshilfen, um Fenster zu lesen und zu verschieben.",
            .accessibilityBannerRequiredTitle: "Bedienungshilfen-Berechtigung erforderlich",
            .accessibilityGranted: "Bedienungshilfen-Berechtigung gewährt",
            .accessibilityPermissionPending: "Bedienungshilfen-Berechtigung ausstehend. Starte Perch neu, wenn es bereits erlaubt ist.",
            .accessibilityPermissionResetEnable: "Bedienungshilfen-Berechtigung zurückgesetzt. Erlaube Perch in den Systemeinstellungen.",
            .addButton: "Hinzufügen",
            .allWindowsRestored: "Alle Fenster wiederhergestellt",
            .appLabel: "App",
            .applicationClosed: "Die Anwendung ist geschlossen.",
            .applicationNotInstalled: "Die Anwendung ist nicht installiert.",
            .autoRestoreAdvanced: "Erweitert",
            .autoRestoreAutomatic: "Automatisch wiederherstellen",
            .autoRestoreDecisionAlreadyOffered: "Vorschlag bereits angezeigt",
            .autoRestoreDecisionDisabled: "deaktiviert",
            .autoRestoreDecisionEmptyLayout: "passendes Layout ist leer",
            .autoRestoreDecisionError: "Entscheidung fehlgeschlagen",
            .autoRestoreDecisionNoLayout: "kein Layout für diese Anordnung",
            .autoRestoreDecisionPromptFormat: "%@ angeboten",
            .autoRestoreDecisionRestoreFormat: "automatische Wiederherstellung gestartet: %@",
            .autoRestoreDecisionTopologyIncomplete: "Display-Anordnung ist noch unvollständig",
            .autoRestoreDecisionTopologyUnchanged: "Display-Anordnung unverändert",
            .autoRestoreDoNothing: "Nichts tun",
            .autoRestoreModeLabel: "Wenn sich Displays ändern",
            .autoRestorePrompt: "Nachfragen",
            .autoRestorePromptFooter: "Perch bietet an, das für diese Display-Anordnung gespeicherte Layout wiederherzustellen.",
            .autoRestoreSectionTitle: "Automatische Wiederherstellung",
            .autoRestoreSettleTimeoutFooter: "Wie lange Perch wartet, bis Dock oder Displays vollständig verbunden sind, bevor die Anordnung geprüft wird.",
            .autoRestoreSettleTimeoutLabel: "Wartezeit für Displays",
            .automaticUpdateChecksToggle: "Automatisch nach Updates suchen",
            .bundleIDLabel: "Bundle-ID",
            .cancelButton: "Abbrechen",
            .checkForUpdatesMenuItem: "Nach Updates suchen…",
            .chooseLayoutName: "Wähle einen Namen für dieses Layout.",
            .clearCustomShortcutHelp: "Eigenes Tastenkürzel löschen",
            .createLayout: "Layout erstellen",
            .createdLayoutFormat: "%@ erstellt",
            .deleteButton: "Löschen",
            .deleteLayoutHelp: "Layout löschen",
            .deleteLayoutMessageFormat: "„%@“ und die gespeicherten Fenster werden entfernt.",
            .deleteLayoutTitle: "Layout löschen?",
            .diagnosticsExported: "Diagnose exportiert",
            .errorSectionTitle: "Fehler",
            .generalTabTitle: "Allgemein",
            .grantAccessibilityPermission: "Bedienungshilfen-Berechtigung gewähren…",
            .grantAccessibilityPermissionPending: "Bedienungshilfen-Berechtigung ausstehend…",
            .hotkeyActionRestoreFormat: "%@ wiederherstellen",
            .hotkeyActionSaveFormat: "%@ speichern",
            .hotkeyRecordPrompt: "Hier klicken und ein Tastenkürzel drücken",
            .hotkeyRequiresModifier: "Mindestens eine Modifikatortaste verwenden",
            .languagePickerLabel: "Sprache",
            .languageSectionTitle: "Sprache",
            .lastAutomaticDecisionFormat: "Automatische Wiederherstellung: %@",
            .lastRestoreReport: "Letzter Wiederherstellungsbericht",
            .launchAtLogin: "Beim Anmelden starten",
            .launchAtLoginStatus: "Status des Anmeldeobjekts",
            .launchDidNotReturnApp: "macOS hat keine laufende App zurückgegeben.",
            .launchStatusDisabled: "Deaktiviert",
            .launchStatusEnabled: "Aktiviert",
            .launchStatusRequiresApproval: "Erfordert Zustimmung in den Systemeinstellungen",
            .launchStatusUnavailable: "Nicht verfügbar",
            .launchStatusUnknown: "Unbekannt",
            .layoutNameCannotBeEmpty: "Der Layoutname darf nicht leer sein.",
            .layoutNameField: "Layoutname",
            .layoutNotFoundFormat: "Layout nicht gefunden: %@",
            .layoutsSectionTitle: "Layouts",
            .layoutsTabTitle: "Layouts",
            .matchReasonOnlyOpenWindow: "einziges offenes Fenster dieser App",
            .matchReasonSameLiveWindow: "dasselbe aktive Fenster",
            .matchReasonSavedWindowIdentity: "gespeicherte Fensteridentität",
            .matchReasonWindowTitle: "Fenstertitel",
            .matchedByLabel: "Zugeordnet über",
            .menuBarFooter: "Wenn deaktiviert, wird in der Menüleiste nur das Perch-Symbol angezeigt.",
            .menuBarSectionTitle: "Menüleiste",
            .menuBarShowLabel: "Beschriftung neben dem Menüleistensymbol anzeigen",
            .menuOutcomeAmbiguousWindows: "mehrdeutige Fenster",
            .menuOutcomeClosed: "geschlossen",
            .menuOutcomeLaunchFailed: "Start fehlgeschlagen",
            .menuOutcomeMoveFailed: "Verschieben fehlgeschlagen",
            .menuOutcomeNotInstalled: "nicht installiert",
            .menuOutcomeOpenedAndRestored: "geöffnet und wiederhergestellt",
            .menuOutcomeRestored: "wiederhergestellt",
            .menuOutcomeSkipped: "übersprungen",
            .menuOutcomeWindowNotFound: "Fenster nicht gefunden",
            .newLayoutDefaultName: "Neues Layout",
            .newLayoutNamePlaceholder: "Name des neuen Layouts",
            .noLayouts: "Noch keine Layouts.",
            .noLayoutsYet: "Noch keine Layouts",
            .noRestoreShortcut: "Kein Wiederherstellungs-Tastenkürzel",
            .noWindowsSaved: "Keine Fenster gespeichert",
            .noWindowsSavedYet: "Noch keine Fenster gespeichert",
            .openMissingAppsDuringRestore: "Fehlende Apps beim Wiederherstellen öffnen",
            .openSystemSettings: "Systemeinstellungen öffnen",
            .openedDuringRestore: "Perch hat diese App während der Wiederherstellung geöffnet.",
            .operationAlreadyRunning: "Ein anderer Speicher- oder Wiederherstellungsvorgang läuft bereits.",
            .quitPerch: "Perch beenden",
            .reasonLabel: "Grund",
            .recordRestoreShortcutHelp: "Tastenkürzel zum Wiederherstellen aufnehmen",
            .refreshButton: "Aktualisieren",
            .resetAccessibilityPermission: "Bedienungshilfen-Berechtigung zurücksetzen…",
            .resetPermissionButton: "Berechtigung zurücksetzen",
            .restartPerch: "Perch neu starten",
            .restoreLayoutFormat: "%@ wiederherstellen",
            .restorePromptButton: "Wiederherstellen",
            .restorePromptDismiss: "Wiederherstellungsvorschlag schließen",
            .restorePromptShortcutFormat: "Zum Wiederherstellen %@ drücken",
            .restorePromptTitleFormat: "%@ wiederherstellen?",
            .restoreSectionFooter: "Wenn deaktiviert, bleiben geschlossene Apps geschlossen und nur aktuell geöffnete Fenster werden verschoben.",
            .restoreSectionTitle: "Wiederherstellen",
            .saveButton: "Sichern",
            .saveCurrentWindowsFormat: "Aktuelle Fenster in „%@“ speichern",
            .settingsMenuItem: "Einstellungen…",
            .settingsWindowTitle: "Perch-Einstellungen",
            .shortcutAlreadyUsedRestoreFormat: "Das Tastenkürzel wird bereits zum Wiederherstellen von %@ verwendet.",
            .shortcutAlreadyUsedSaveFormat: "Das Tastenkürzel wird bereits zum Speichern von %@ verwendet.",
            .shortcutRejectedTooltipFormat: "macOS hat dieses Tastenkürzel mit Status %d abgelehnt. Es wird möglicherweise bereits vom System oder einer anderen App verwendet.",
            .shortcutUnavailableTooltipFormat: "Das Tastenkürzel %@ konnte nicht registriert werden. Möglicherweise wird es bereits von macOS oder einer anderen App verwendet.",
            .slotNotFoundFormat: "Slot nicht gefunden: %@",
            .someShortcutsUnavailable: "Einige Tastenkürzel sind nicht verfügbar",
            .startupSectionTitle: "Start",
            .updateLayoutWindowsFormat: "„%@“ mit aktuellen Fenstern aktualisieren",
            .updatesSectionTitle: "Updates",
            .windowLabel: "Fenster",
            .windowsAndShortcutFormat: "%d %@ · %@"
        ]
    ]
}
