extension LocalizationCatalog {
    static let german: [LocalizationKey: String] = [
        .captureCurrentLayout: "Aktuelle Anordnung speichern",
        .captureLayoutHelp: "Speichert die Positionen der geöffneten Fenster. Beim Aktualisieren bleibt die vorherige Version erhalten.",
        .automaticLayoutTitle: "Anordnung für angeschlossene Displays",
        .latestMatchingLayout: "Zuletzt gespeichert",
        .selectedAutomaticLayoutFormat: "Nächste automatische Wiederherstellung: %@",
        .noMatchingSavedLayout: "Speichere eine Anordnung mit diesen Displays für die automatische Auswahl.",
        .preferredForDisplays: "Bevorzugt für diese Displays",
        .useForAutomaticRestore: "Für automatische Wiederherstellung bevorzugen",
        .followLatestSaved: "Wieder die zuletzt gespeicherte verwenden",
        .lastSavedLabel: "Zuletzt gespeichert",
        .savedDisplaysFormat: "Displays: %d",
        .layoutDetails: "Details der Anordnung",
        .layoutHistory: "Gespeicherte Versionen",
        .noLayoutHistory: "Vorherige Versionen erscheinen hier, sobald du eine gespeicherte Anordnung aktualisierst oder löschst.",
        .historyExplanation: "Auf diesem Mac bleiben bis zu 10 Versionen je Anordnung, insgesamt 100. Das Wiederherstellen einer Version ändert die gespeicherte Anordnung, ohne Fenster zu verschieben.",
        .restoreVersion: "Diese Version wiederherstellen",
        .historyRestored: "Gespeicherte Version wiederhergestellt. Ihre Fenster lassen sich über das Anordnungsmenü wiederherstellen.",
        .unknownDisplayArrangement: "Display-Anordnung nicht gespeichert",
        .assignOpenWindow: "Geöffnetes Fenster zuordnen…",
        .chooseOpenWindow: "Wähle das Fenster für diese gespeicherte Position. Die Zielposition bleibt erhalten.",
        .windowReassigned: "Fenster zugeordnet. Erneut versuchen, um es an die gespeicherte Position zu verschieben.",
        .noOpenWindowsForApp: "In dieser App sind keine verschiebbaren Fenster geöffnet. Öffne das gewünschte Fenster und aktualisiere die Liste.",
        .useThisWindow: "Dieses Fenster verwenden",
        .retryRemaining: "Verbleibende Fenster erneut versuchen",
        .retryWindow: "Erneut versuchen",
        .openAndRetry: "App öffnen und erneut versuchen",
        .restoreActivity: "Fortschritt und Ergebnis",
        .stopRestore: "Verbleibende Arbeit stoppen",
        .stoppingRestore: "Wird gestoppt… Abgeschlossene Verschiebungen bleiben erhalten.",
        .waitingForDisplays: "Warte auf stabile Displays…",
        .workingOnApplicationFormat: "Fenster werden wiederhergestellt: %@",
        .restoreProgressFormat: "%d von %d Fenstern verarbeitet",
        .undoLastRestore: "Letzte Wiederherstellung rückgängig machen",
        .undoExplanation: "Setzt verschobene Fenster auf denselben Displays zurück. Geschlossene oder ersetzte Fenster werden übersprungen. Verfügbar bis zur nächsten Wiederherstellung oder zum App-Neustart.",
        .undoResults: "Ergebnis des Rückgängigmachens",
        .outcomePending: "Wartet",
        .outcomeCancelled: "Gestoppt",
        .noRestoreYet: "Stelle eine Anordnung wieder her, um hier Fortschritt und Ergebnis zu sehen.",
        .reportHelp: "Erneut versucht werden nur unvollständige Fenster. Das Öffnen einer App hier ändert keine automatischen Einstellungen und erstellt keine geschlossenen Dokumente oder Tabs neu.",
        .closeButton: "Schließen",
        .noWindowsToCapture: "Es sind keine verschiebbaren Fenster geöffnet. Öffne die gewünschten Fenster und versuche es erneut.",
        .layoutChangedSinceRestore: "Diese Anordnung wurde geändert. Stelle vor einzelnen Wiederholungen ihre aktuelle Version wieder her.",
        .repairWindowUnavailable: "Das gewählte Fenster ist nicht mehr verfügbar. Aktualisiere die Liste und wähle erneut.",
        .nothingToUndo: "Keine Fensterverschiebungen zum Rückgängigmachen.",
        .undoDisplayConfigurationChanged: "Verbinde dieselbe Display-Anordnung, bevor du die Verschiebungen rückgängig machst.",
        .windowAlreadyAssigned: "Dieses Fenster ist bereits einer anderen Position dieser Anordnung zugeordnet.",
        .untitledWindow: "Fenster ohne Titel",
        .storeRecoveryTitle: "Gespeicherte Layouts benötigen Aufmerksamkeit",
        .storeRecoveryMessage: "Einige gespeicherte Layouts konnten nicht gelesen werden. Perch hat die Originaldateien zur Wiederherstellung aufbewahrt. Behalten Sie sie, bis Sie eine gültige Sicherung wiederherstellen oder das Problem mit dem Support lösen.",
        .storeRecoveryShowFiles: "Aufbewahrte Dateien anzeigen",
        .storeRecoveryDismiss: "Hinweis schließen",
        .applicationLaunchTimedOut: "Die Anwendung wurde nicht rechtzeitig gestartet. Sie kann sich später öffnen. Stellen Sie das Layout erneut her, sobald sie bereit ist.",
        .autoRestoreAutomaticFooter: "Stellt nach dem Entsperren und Stabilisieren der Displays ohne Bestätigung die bevorzugte oder zuletzt gespeicherte passende Anordnung wieder her. Aktiviere Start bei Anmeldung für die Wiederherstellung nach einem Neustart.",
        .displaysChangedDuringSave: "Die Displays haben sich beim Speichern geändert. Warte, bis sie bereit sind, und speichere das Layout erneut.",
        .aboutAccessibilityLabel: "Bedienungshilfen",
        .aboutDescriptionPrivacy: "Layouts bleiben auf diesem Mac. Perch liest Fenster beim Speichern und verschiebt sie bei manuellen Wiederherstellungen oder wenn die automatische Wiederherstellung aktiviert ist.",
        .aboutDescriptionRestore: "Erstelle benannte Layouts für Arbeit, Fokus, Meetings oder anderes. Stelle sie über die Menüleiste oder Tastenkürzel wieder her, auch über mehrere Displays hinweg.",
        .aboutDescriptionSummary: "Perch ist eine ruhige Menüleisten-App zum Speichern deiner Mac-Fensteranordnung und zum Wiederherstellen desselben Arbeitsbereichs.",
        .aboutDiagnosticsRedacted: "Diagnosedaten sind redigiert, nicht anonym. Sie enthalten App- und Layout-IDs, Displaygeometrie, Anzahlen, Zeitangaben, Einstellungen und Systemdaten. Fenstertitel und Layoutnamen sind ausgeschlossen.",
        .aboutExportDiagnostics: "Diagnose exportieren…",
        .aboutGranted: "Gewährt",
        .aboutMadeBy: "Erstellt von Code&live",
        .aboutMissing: "Fehlt",
        .aboutTabTitle: "Info",
        .aboutVersionFormat: "Version %@",
        .accessibilityBannerPendingMessage: "Wenn Perch in den Systemeinstellungen bereits erlaubt ist, starte es neu, damit macOS die Berechtigung der laufenden App zuordnet.",
        .accessibilityBannerPendingTitle: "Bedienungshilfen-Berechtigung ausstehend",
        .accessibilityBannerRequiredMessage: "Perch benötigt Zugriff auf Bedienungshilfen, um Fenster zu lesen und zu verschieben.",
        .accessibilityBannerRequiredTitle: "Bedienungshilfen-Berechtigung erforderlich",
        .accessibilityGranted: "Bedienungshilfen-Berechtigung gewährt",
        .accessibilityPermissionPending: "Bedienungshilfen-Berechtigung ausstehend. Starte Perch neu, wenn es bereits erlaubt ist.",
        .accessibilityPermissionResetEnable: "Bedienungshilfen-Berechtigung zurückgesetzt. Erlaube Perch in den Systemeinstellungen.",
        .addButton: "Hinzufügen",
        .allWindowsRestored: "Alle Fenster wiederhergestellt",
        .appLabel: "App",
        .applicationClosed: "Die Anwendung ist geschlossen.",
        .applicationNotInstalled: "Die Anwendung ist nicht installiert.",
        .autoRestoreAdvanced: "Erweitert",
        .autoRestoreAutomatic: "Automatisch wiederherstellen",
        .autoRestoreDecisionAlreadyOffered: "Vorschlag bereits angezeigt",
        .autoRestoreDecisionDisabled: "deaktiviert",
        .autoRestoreDecisionEmptyLayout: "passendes Layout ist leer",
        .autoRestoreDecisionError: "Entscheidung fehlgeschlagen",
        .autoRestoreDecisionNoLayout: "kein Layout für diese Anordnung",
        .autoRestoreDecisionPromptFormat: "%@ angeboten",
        .autoRestoreDecisionRestoreFormat: "automatische Wiederherstellung gestartet: %@",
        .autoRestoreDecisionTopologyIncomplete: "Display-Anordnung ist noch unvollständig",
        .autoRestoreDecisionTopologyUnchanged: "Display-Anordnung unverändert",
        .autoRestoreDoNothing: "Nichts tun",
        .autoRestoreModeLabel: "Beim Start, Aufwachen oder Display-Wechsel",
        .autoRestorePrompt: "Nachfragen",
        .autoRestorePromptFooter: "Perch bietet an, das für diese Display-Anordnung gespeicherte Layout wiederherzustellen.",
        .autoRestoreSectionTitle: "Automatische Wiederherstellung",
        .autoRestoreSettleTimeoutFooter: "Wie lange Perch wartet, bis Dock oder Displays vollständig verbunden sind, bevor die Anordnung geprüft wird.",
        .autoRestoreSettleTimeoutLabel: "Wartezeit für Displays",
        .automaticUpdateChecksToggle: "Automatisch nach Updates suchen",
        .bundleIDLabel: "Bundle-ID",
        .cancelButton: "Abbrechen",
        .checkForUpdatesMenuItem: "Nach Updates suchen…",
        .chooseLayoutName: "Wähle einen Namen für dieses Layout.",
        .clearCustomShortcutHelp: "Eigenes Tastenkürzel löschen",
        .createLayout: "Layout erstellen",
        .createdLayoutFormat: "%@ erstellt",
        .deleteButton: "Löschen",
        .deleteLayoutHelp: "Layout löschen",
        .deleteLayoutMessageFormat: "„%@“ und die gespeicherten Fenster werden entfernt.",
        .deleteLayoutTitle: "Layout löschen?",
        .diagnosticsExported: "Diagnose exportiert",
        .errorSectionTitle: "Fehler",
        .generalTabTitle: "Allgemein",
        .grantAccessibilityPermission: "Bedienungshilfen-Berechtigung gewähren…",
        .grantAccessibilityPermissionPending: "Bedienungshilfen-Berechtigung ausstehend…",
        .hotkeyActionRestoreFormat: "%@ wiederherstellen",
        .hotkeyActionSaveFormat: "%@ speichern",
        .hotkeyRecordPrompt: "Hier klicken und ein Tastenkürzel drücken",
        .hotkeyRequiresModifier: "Mindestens eine Modifikatortaste verwenden",
        .languagePickerLabel: "Sprache",
        .languageSectionTitle: "Sprache",
        .lastAutomaticDecisionFormat: "Automatische Wiederherstellung: %@",
        .lastRestoreReport: "Letzter Wiederherstellungsbericht",
        .launchAtLogin: "Beim Anmelden starten",
        .launchAtLoginStatus: "Status des Anmeldeobjekts",
        .launchDidNotReturnApp: "macOS hat keine laufende App zurückgegeben.",
        .launchStatusDisabled: "Deaktiviert",
        .launchStatusEnabled: "Aktiviert",
        .launchStatusRequiresApproval: "Erfordert Zustimmung in den Systemeinstellungen",
        .launchStatusUnavailable: "Nicht verfügbar",
        .launchStatusUnknown: "Unbekannt",
        .layoutNameCannotBeEmpty: "Der Layoutname darf nicht leer sein.",
        .layoutNameField: "Layoutname",
        .layoutNotFoundFormat: "Layout nicht gefunden: %@",
        .layoutsSectionTitle: "Layouts",
        .layoutsTabTitle: "Layouts",
        .matchReasonOnlyOpenWindow: "einziges offenes Fenster dieser App",
        .matchReasonSameLiveWindow: "dasselbe aktive Fenster",
        .matchReasonSavedWindowIdentity: "gespeicherte Fensteridentität",
        .matchReasonWindowTitle: "Fenstertitel",
        .matchedByLabel: "Zugeordnet über",
        .menuBarFooter: "Wenn deaktiviert, wird in der Menüleiste nur das Perch-Symbol angezeigt.",
        .menuBarSectionTitle: "Menüleiste",
        .menuBarShowLabel: "Beschriftung neben dem Menüleistensymbol anzeigen",
        .menuOutcomeAmbiguousWindows: "mehrdeutige Fenster",
        .menuOutcomeClosed: "geschlossen",
        .menuOutcomeLaunchFailed: "Start fehlgeschlagen",
        .menuOutcomeMoveFailed: "Verschieben fehlgeschlagen",
        .menuOutcomeNotInstalled: "nicht installiert",
        .menuOutcomeOpenedAndRestored: "geöffnet und wiederhergestellt",
        .menuOutcomeRestored: "wiederhergestellt",
        .menuOutcomeSkipped: "übersprungen",
        .menuOutcomeWindowNotFound: "Fenster nicht gefunden",
        .newLayoutDefaultName: "Neues Layout",
        .newLayoutNamePlaceholder: "Name des neuen Layouts",
        .noLayouts: "Noch keine Layouts.",
        .noLayoutsYet: "Noch keine Layouts",
        .noRestoreShortcut: "Kein Wiederherstellungs-Tastenkürzel",
        .noWindowsSaved: "Keine Fenster gespeichert",
        .noWindowsSavedYet: "Noch keine Fenster gespeichert",
        .openMissingAppsDuringRestore: "Fehlende Apps beim Wiederherstellen öffnen",
        .openSystemSettings: "Systemeinstellungen öffnen",
        .openedDuringRestore: "Perch hat diese App während der Wiederherstellung geöffnet.",
        .operationAlreadyRunning: "Ein anderer Speicher- oder Wiederherstellungsvorgang läuft bereits.",
        .quitPerch: "Perch beenden",
        .reasonLabel: "Grund",
        .recordRestoreShortcutHelp: "Tastenkürzel zum Wiederherstellen aufnehmen",
        .refreshButton: "Aktualisieren",
        .resetAccessibilityPermission: "Bedienungshilfen-Berechtigung zurücksetzen…",
        .resetPermissionButton: "Berechtigung zurücksetzen",
        .restartPerch: "Perch neu starten",
        .restoreLayoutFormat: "%@ wiederherstellen",
        .restorePromptButton: "Wiederherstellen",
        .restorePromptDismiss: "Wiederherstellungsvorschlag schließen",
        .restorePromptShortcutFormat: "Zum Wiederherstellen %@ drücken",
        .restorePromptTitleFormat: "%@ wiederherstellen?",
        .restoreSectionFooter: "Wenn deaktiviert, bleiben geschlossene Apps geschlossen und nur aktuell geöffnete Fenster werden verschoben.",
        .restoreSectionTitle: "Wiederherstellen",
        .saveButton: "Sichern",
        .saveCurrentWindowsFormat: "Aktuelle Fenster in „%@“ speichern",
        .settingsMenuItem: "Einstellungen…",
        .settingsWindowTitle: "Perch-Einstellungen",
        .shortcutAlreadyUsedRestoreFormat: "Das Tastenkürzel wird bereits zum Wiederherstellen von %@ verwendet.",
        .shortcutAlreadyUsedSaveFormat: "Das Tastenkürzel wird bereits zum Speichern von %@ verwendet.",
        .shortcutRejectedTooltipFormat: "macOS hat dieses Tastenkürzel mit Status %d abgelehnt. Es wird möglicherweise bereits vom System oder einer anderen App verwendet.",
        .shortcutUnavailableTooltipFormat: "Das Tastenkürzel %@ konnte nicht registriert werden. Möglicherweise wird es bereits von macOS oder einer anderen App verwendet.",
        .slotNotFoundFormat: "Slot nicht gefunden: %@",
        .someShortcutsUnavailable: "Einige Tastenkürzel sind nicht verfügbar",
        .startupSectionTitle: "Start",
        .updateLayoutWindowsFormat: "„%@“ mit aktuellen Fenstern aktualisieren",
        .updatesSectionTitle: "Updates",
        .windowLabel: "Fenster",
        .windowsAndShortcutFormat: "%d %@ · %@"
    ]
}
