extension LocalizationCatalog {
    static let slovak: [LocalizationKey: String] = [
        .storeRecoveryTitle: "Uložené rozloženia vyžadujú pozornosť",
        .storeRecoveryMessage: "Niektoré uložené rozloženia sa nepodarilo načítať. Perch zachoval pôvodné súbory na obnovu. Ponechajte ich, kým neobnovíte platnú zálohu alebo problém nevyriešite s podporou.",
        .storeRecoveryShowFiles: "Ukázať zachované súbory",
        .storeRecoveryDismiss: "Zavrieť upozornenie",
        .applicationLaunchTimedOut: "Aplikácia sa nestihla spustiť. Môže sa otvoriť neskôr; keď bude pripravená, skúste rozloženie obnoviť znova.",
        .autoRestoreAutomaticFooter: "Obnoví naposledy uložené rozloženie pre pripojené displeje. Ak už používate klávesnicu alebo myš, Perch sa najprv opýta. Pre obnovu po reštarte zapnite Spúšťať pri prihlásení.",
        .displaysChangedDuringSave: "Počas ukladania sa zmenili displeje. Počkajte na ich ustálenie a uložte rozloženie znova.",
        .aboutAccessibilityLabel: "Prístupnosť",
        .aboutDescriptionPrivacy: "Rozloženia zostávajú na tomto Macu. Perch číta okná pri ukladaní a presúva ich pri ručnom obnovení alebo keď je zapnuté automatické obnovenie.",
        .aboutDescriptionRestore: "Vytvárajte pomenované rozloženia pre prácu, sústredenie, schôdzky alebo čokoľvek ďalšie. Obnovíte ich z lišty alebo klávesovou skratkou, aj cez viac displejov.",
        .aboutDescriptionSummary: "Perch je nenápadná aplikácia v lište na ukladanie rozloženia okien na Macu a jeho obnovenie, keď znova potrebujete rovnaký pracovný priestor.",
        .aboutDiagnosticsRedacted: "Diagnostika je redigovaná, nie anonymná. Obsahuje identifikátory aplikácií a rozložení, geometriu displejov, počty, časové údaje, nastavenia a údaje o systéme. Názvy okien a rozložení sa neexportujú.",
        .aboutExportDiagnostics: "Exportovať diagnostiku…",
        .aboutGranted: "Povolené",
        .aboutMadeBy: "Vytvorilo Code&live",
        .aboutMissing: "Chýba",
        .aboutTabTitle: "O aplikácii",
        .aboutVersionFormat: "Verzia %@",
        .accessibilityBannerPendingMessage: "Ak je Perch už povolený v Nastaveniach systému, reštartujte ho, aby macOS pripojil oprávnenie k bežiacej aplikácii.",
        .accessibilityBannerPendingTitle: "Oprávnenie Prístupnosť čaká",
        .accessibilityBannerRequiredMessage: "Perch potrebuje prístup k Prístupnosti, aby mohol čítať a presúvať okná.",
        .accessibilityBannerRequiredTitle: "Vyžaduje sa oprávnenie Prístupnosť",
        .accessibilityGranted: "Oprávnenie Prístupnosť povolené",
        .accessibilityPermissionPending: "Oprávnenie Prístupnosť čaká. Ak je Perch už povolený, reštartujte ho.",
        .accessibilityPermissionResetEnable: "Oprávnenie Prístupnosť resetované. Povoľte Perch v Nastaveniach systému.",
        .addButton: "Pridať",
        .allWindowsRestored: "Všetky okná obnovené",
        .appLabel: "Aplikácia",
        .applicationClosed: "Aplikácia je zatvorená.",
        .applicationNotInstalled: "Aplikácia nie je nainštalovaná.",
        .autoRestoreAdvanced: "Pokročilé",
        .autoRestoreAutomatic: "Obnoviť automaticky",
        .autoRestoreDecisionAlreadyOffered: "ponuka už bola zobrazená",
        .autoRestoreDecisionDisabled: "vypnuté",
        .autoRestoreDecisionEmptyLayout: "zodpovedajúce rozloženie je prázdne",
        .autoRestoreDecisionError: "rozhodnutie zlyhalo",
        .autoRestoreDecisionNoLayout: "pre túto zostavu nie je rozloženie",
        .autoRestoreDecisionPromptFormat: "ponúknuté %@",
        .autoRestoreDecisionRestoreFormat: "spustené automatické obnovenie: %@",
        .autoRestoreDecisionTopologyIncomplete: "zostava displejov ešte nie je kompletná",
        .autoRestoreDecisionTopologyUnchanged: "zostava displejov sa nezmenila",
        .autoRestoreDoNothing: "Nerobiť nič",
        .autoRestoreModeLabel: "Pri spustení, prebudení alebo zmene displejov",
        .autoRestorePrompt: "Opýtať sa",
        .autoRestorePromptFooter: "Perch ponúkne obnovenie rozloženia uloženého pre túto zostavu displejov.",
        .autoRestoreSectionTitle: "Automatické obnovenie",
        .autoRestoreSettleTimeoutFooter: "Ako dlho Perch čaká, kým sa dok alebo displeje dokončia pripájať, a až potom skontroluje zostavu.",
        .autoRestoreSettleTimeoutLabel: "Čas na ustálenie displejov",
        .automaticUpdateChecksToggle: "Automaticky kontrolovať aktualizácie",
        .bundleIDLabel: "Bundle ID",
        .cancelButton: "Zrušiť",
        .checkForUpdatesMenuItem: "Skontrolovať aktualizácie…",
        .chooseLayoutName: "Zvoľte názov tohto rozloženia.",
        .clearCustomShortcutHelp: "Vymazať vlastnú skratku",
        .createLayout: "Vytvoriť rozloženie",
        .createdLayoutFormat: "Vytvorené %@",
        .deleteButton: "Vymazať",
        .deleteLayoutHelp: "Vymazať rozloženie",
        .deleteLayoutMessageFormat: "„%@“ a jeho uložené okná budú odstránené.",
        .deleteLayoutTitle: "Vymazať rozloženie?",
        .diagnosticsExported: "Diagnostika exportovaná",
        .errorSectionTitle: "Chyba",
        .generalTabTitle: "Všeobecné",
        .grantAccessibilityPermission: "Udeliť oprávnenie Prístupnosť…",
        .grantAccessibilityPermissionPending: "Oprávnenie Prístupnosť čaká…",
        .hotkeyActionRestoreFormat: "obnoviť %@",
        .hotkeyActionSaveFormat: "uložiť %@",
        .hotkeyRecordPrompt: "Kliknite sem a stlačte skratku",
        .hotkeyRequiresModifier: "Použite aspoň jeden modifikátor",
        .languagePickerLabel: "Jazyk",
        .languageSectionTitle: "Jazyk",
        .lastAutomaticDecisionFormat: "Automatické obnovenie: %@",
        .lastRestoreReport: "Posledné hlásenie obnovenia",
        .launchAtLogin: "Spustiť po prihlásení",
        .launchAtLoginStatus: "Stav položky prihlásenia",
        .launchDidNotReturnApp: "macOS nevrátil bežiacu aplikáciu.",
        .launchStatusDisabled: "Vypnuté",
        .launchStatusEnabled: "Zapnuté",
        .launchStatusRequiresApproval: "Vyžaduje schválenie v Nastaveniach systému",
        .launchStatusUnavailable: "Nedostupné",
        .launchStatusUnknown: "Neznáme",
        .layoutNameCannotBeEmpty: "Názov rozloženia nesmie byť prázdny.",
        .layoutNameField: "Názov rozloženia",
        .layoutNotFoundFormat: "Rozloženie nenájdené: %@",
        .layoutsSectionTitle: "Rozloženia",
        .layoutsTabTitle: "Rozloženia",
        .matchReasonOnlyOpenWindow: "jediné otvorené okno tejto aplikácie",
        .matchReasonSameLiveWindow: "rovnaké živé okno",
        .matchReasonSavedWindowIdentity: "uložená identita okna",
        .matchReasonWindowTitle: "titulok okna",
        .matchedByLabel: "Zhoda podľa",
        .menuBarFooter: "Keď je voľba vypnutá, v lište sa zobrazí iba ikona Perch.",
        .menuBarSectionTitle: "Lišta menu",
        .menuBarShowLabel: "Zobraziť popis vedľa ikony v lište",
        .menuOutcomeAmbiguousWindows: "nejednoznačné okná",
        .menuOutcomeClosed: "zatvorené",
        .menuOutcomeLaunchFailed: "spustenie zlyhalo",
        .menuOutcomeMoveFailed: "presun zlyhal",
        .menuOutcomeNotInstalled: "nie je nainštalované",
        .menuOutcomeOpenedAndRestored: "otvorené a obnovené",
        .menuOutcomeRestored: "obnovené",
        .menuOutcomeSkipped: "preskočené",
        .menuOutcomeWindowNotFound: "okno nenájdené",
        .newLayoutDefaultName: "Nové rozloženie",
        .newLayoutNamePlaceholder: "Názov nového rozloženia",
        .noLayouts: "Zatiaľ žiadne rozloženia.",
        .noLayoutsYet: "Zatiaľ žiadne rozloženia",
        .noRestoreShortcut: "Žiadna skratka pre obnovenie",
        .noWindowsSaved: "Nie sú uložené žiadne okná",
        .noWindowsSavedYet: "Zatiaľ nie sú uložené žiadne okná",
        .openMissingAppsDuringRestore: "Pri obnovení otvoriť chýbajúce aplikácie",
        .openSystemSettings: "Otvoriť Nastavenia systému",
        .openedDuringRestore: "Perch túto aplikáciu počas obnovenia otvoril.",
        .operationAlreadyRunning: "Iné ukladanie alebo obnovovanie práve beží.",
        .quitPerch: "Ukončiť Perch",
        .reasonLabel: "Dôvod",
        .recordRestoreShortcutHelp: "Nahrať skratku pre obnovenie",
        .refreshButton: "Obnoviť",
        .resetAccessibilityPermission: "Resetovať oprávnenie Prístupnosť…",
        .resetPermissionButton: "Resetovať oprávnenie",
        .restartPerch: "Reštartovať Perch",
        .restoreLayoutFormat: "Obnoviť %@",
        .restorePromptButton: "Obnoviť",
        .restorePromptDismiss: "Zavrieť ponuku obnovenia",
        .restorePromptShortcutFormat: "Obnovíte stlačením %@",
        .restorePromptTitleFormat: "Obnoviť %@?",
        .restoreSectionFooter: "Keď je voľba vypnutá, zatvorené aplikácie zostanú zatvorené a presunú sa iba aktuálne otvorené okná.",
        .restoreSectionTitle: "Obnovenie",
        .saveButton: "Uložiť",
        .saveCurrentWindowsFormat: "Uložiť aktuálne okná do „%@“",
        .settingsMenuItem: "Nastavenia…",
        .settingsWindowTitle: "Nastavenia Perch",
        .shortcutAlreadyUsedRestoreFormat: "Skratka sa už používa na obnovenie %@.",
        .shortcutAlreadyUsedSaveFormat: "Skratka sa už používa na uloženie %@.",
        .shortcutRejectedTooltipFormat: "macOS odmietol túto skratku so stavom %d. Možno ju už používa systém alebo iná aplikácia.",
        .shortcutUnavailableTooltipFormat: "Skratku %@ sa nepodarilo zaregistrovať. Možno ju už používa macOS alebo iná aplikácia.",
        .slotNotFoundFormat: "Slot nenájdený: %@",
        .someShortcutsUnavailable: "Niektoré skratky nie sú dostupné",
        .startupSectionTitle: "Spustenie",
        .updateLayoutWindowsFormat: "Aktualizovať „%@“ aktuálnymi oknami",
        .updatesSectionTitle: "Aktualizácie",
        .windowLabel: "Okno",
        .windowsAndShortcutFormat: "%d %@ · %@"
    ]
}
