extension LocalizationCatalog {
    static let english: [LocalizationKey: String] = [
        .captureCurrentLayout: "Save Current Layout",
        .captureLayoutHelp: "Saves the positions of your currently open windows. Previous versions are kept when you update a layout.",
        .automaticLayoutTitle: "Layout for Connected Displays",
        .latestMatchingLayout: "Most Recently Saved",
        .selectedAutomaticLayoutFormat: "Next automatic restore: %@",
        .noMatchingSavedLayout: "Save a layout with these displays to enable automatic matching.",
        .preferredForDisplays: "Preferred for These Displays",
        .useForAutomaticRestore: "Prefer for Automatic Restore",
        .followLatestSaved: "Use Most Recently Saved Again",
        .lastSavedLabel: "Last saved",
        .savedDisplaysFormat: "Displays: %d",
        .layoutDetails: "Layout Details",
        .layoutHistory: "Saved Versions",
        .noLayoutHistory: "Previous versions will appear here after you update or delete a saved layout.",
        .historyExplanation: "Kept on this Mac: up to 10 versions per layout, 100 in total. Restoring a version changes the saved layout; it does not move windows.",
        .restoreVersion: "Recover This Version",
        .historyRestored: "Saved version recovered. You can restore its windows from the layout menu.",
        .unknownDisplayArrangement: "Display arrangement not recorded",
        .assignOpenWindow: "Assign an Open Window…",
        .chooseOpenWindow: "Choose the window that belongs in this saved position. Its destination stays the same.",
        .windowReassigned: "Window assigned. Retry to move it to the saved position.",
        .noOpenWindowsForApp: "No movable windows are open in this application. Open the desired window, then refresh.",
        .useThisWindow: "Use This Window",
        .retryRemaining: "Retry Remaining Windows",
        .retryWindow: "Retry",
        .openAndRetry: "Open App and Retry",
        .restoreActivity: "Restore Progress and Results",
        .stopRestore: "Stop Remaining Work",
        .stoppingRestore: "Stopping… Completed moves are kept.",
        .waitingForDisplays: "Waiting for displays to settle…",
        .workingOnApplicationFormat: "Restoring windows: %@",
        .restoreProgressFormat: "Processed %d of %d windows",
        .undoLastRestore: "Undo Last Restore",
        .undoExplanation: "Returns moved windows to their previous positions on the same displays. Closed or replaced windows are skipped. Available until the next restore or app restart.",
        .undoResults: "Undo Results",
        .outcomePending: "Waiting",
        .outcomeCancelled: "Stopped",
        .noRestoreYet: "Restore a layout to see its progress and results here.",
        .reportHelp: "Retry affects only unfinished windows. Opening an app here does not change your automatic restore settings or recreate closed documents and tabs.",
        .closeButton: "Close",
        .noWindowsToCapture: "No movable windows are open. Open the windows you want to save and try again.",
        .layoutChangedSinceRestore: "This layout has changed. Restore its current version before retrying individual windows.",
        .repairWindowUnavailable: "The selected window is no longer available. Refresh the list and choose again.",
        .nothingToUndo: "There are no window moves to undo.",
        .undoDisplayConfigurationChanged: "Reconnect the same display arrangement before undoing these moves.",
        .windowAlreadyAssigned: "This window is already assigned to another position in this layout.",
        .untitledWindow: "Untitled Window",
        .storeRecoveryTitle: "Saved layouts need attention",
        .storeRecoveryMessage: "Some saved layouts could not be read. Perch kept the original files for recovery. Keep them until you restore a valid backup or resolve the problem with support.",
        .storeRecoveryShowFiles: "Show Preserved Files",
        .storeRecoveryDismiss: "Dismiss Notice",
        .applicationLaunchTimedOut: "The application did not finish starting in time. It may open later; try restoring again once it is ready.",
        .autoRestoreAutomaticFooter: "After unlocking and display settling, restores your preferred layout for these displays, or the most recently saved matching layout, without confirmation. Enable Launch at login to use this after a restart.",
        .displaysChangedDuringSave: "Displays changed while saving. Wait for them to settle and save the layout again.",
        .aboutAccessibilityLabel: "Accessibility",
        .aboutDescriptionPrivacy: "Layouts stay on this Mac. Perch reads windows when saving and moves them for manual restores or when automatic restore is enabled.",
        .aboutDescriptionRestore: "Create named layouts for work, focus, meetings, or anything else. Restore them from the menu bar or with keyboard shortcuts, even across multiple displays.",
        .aboutDescriptionSummary: "Perch is a quiet menu bar app for saving your Mac window setup and restoring it when you need the same workspace again.",
        .aboutDiagnosticsRedacted: "Diagnostics are redacted, not anonymous. They include app and layout identifiers, display geometry, counts, timestamps, settings, and system details. Window titles and layout names are excluded.",
        .aboutExportDiagnostics: "Export Diagnostics…",
        .aboutGranted: "Granted",
        .aboutMadeBy: "Made by Code&live",
        .aboutMissing: "Missing",
        .aboutTabTitle: "About",
        .aboutVersionFormat: "Version %@",
        .accessibilityBannerPendingMessage: "If Perch is already enabled in System Settings, restart it so macOS attaches the permission to the running app.",
        .accessibilityBannerPendingTitle: "Accessibility permission pending",
        .accessibilityBannerRequiredMessage: "Perch needs Accessibility access to read and move windows.",
        .accessibilityBannerRequiredTitle: "Accessibility permission required",
        .accessibilityGranted: "Accessibility permission granted",
        .accessibilityPermissionPending: "Accessibility permission pending. Restart Perch if it is already enabled.",
        .accessibilityPermissionResetEnable: "Accessibility permission reset. Enable Perch in System Settings.",
        .addButton: "Add",
        .allWindowsRestored: "All windows restored",
        .appLabel: "App",
        .applicationClosed: "Application is closed.",
        .applicationNotInstalled: "Application is not installed.",
        .autoRestoreAdvanced: "Advanced",
        .autoRestoreAutomatic: "Restore automatically",
        .autoRestoreDecisionAlreadyOffered: "suggestion already shown",
        .autoRestoreDecisionDisabled: "disabled",
        .autoRestoreDecisionEmptyLayout: "matching layout is empty",
        .autoRestoreDecisionError: "decision failed",
        .autoRestoreDecisionNoLayout: "no layout for this arrangement",
        .autoRestoreDecisionPromptFormat: "offered %@",
        .autoRestoreDecisionRestoreFormat: "started automatic restore for %@",
        .autoRestoreDecisionTopologyIncomplete: "display arrangement is still incomplete",
        .autoRestoreDecisionTopologyUnchanged: "display arrangement unchanged",
        .autoRestoreDoNothing: "Do nothing",
        .autoRestoreModeLabel: "On startup, wake, or display changes",
        .autoRestorePrompt: "Ask me",
        .autoRestorePromptFooter: "Perch will offer to restore the layout saved for this display arrangement.",
        .autoRestoreSectionTitle: "Automatic restore",
        .autoRestoreSettleTimeoutFooter: "How long Perch waits for a dock or displays to finish connecting before checking the arrangement.",
        .autoRestoreSettleTimeoutLabel: "Display settle timeout",
        .automaticUpdateChecksToggle: "Automatically check for updates",
        .bundleIDLabel: "Bundle ID",
        .cancelButton: "Cancel",
        .checkForUpdatesMenuItem: "Check for Updates…",
        .chooseLayoutName: "Choose a name for this layout.",
        .clearCustomShortcutHelp: "Clear custom shortcut",
        .createLayout: "Create Layout",
        .createdLayoutFormat: "Created %@",
        .deleteButton: "Delete",
        .deleteLayoutHelp: "Delete layout",
        .deleteLayoutMessageFormat: "“%@” and its saved windows will be removed.",
        .deleteLayoutTitle: "Delete layout?",
        .diagnosticsExported: "Diagnostics exported",
        .errorSectionTitle: "Error",
        .generalTabTitle: "General",
        .grantAccessibilityPermission: "Grant Accessibility Permission…",
        .grantAccessibilityPermissionPending: "Accessibility Permission Pending…",
        .hotkeyActionRestoreFormat: "restore %@",
        .hotkeyActionSaveFormat: "save %@",
        .hotkeyRecordPrompt: "Click here, then press a shortcut",
        .hotkeyRequiresModifier: "Use at least one modifier",
        .languagePickerLabel: "Language",
        .languageSectionTitle: "Language",
        .lastAutomaticDecisionFormat: "Automatic restore: %@",
        .lastRestoreReport: "Last Restore Report",
        .launchAtLogin: "Launch at login",
        .launchAtLoginStatus: "Login item status",
        .launchDidNotReturnApp: "macOS did not return a running application.",
        .launchStatusDisabled: "Disabled",
        .launchStatusEnabled: "Enabled",
        .launchStatusRequiresApproval: "Requires approval in System Settings",
        .launchStatusUnavailable: "Unavailable",
        .launchStatusUnknown: "Unknown",
        .layoutNameCannotBeEmpty: "Layout name cannot be empty.",
        .layoutNameField: "Layout name",
        .layoutNotFoundFormat: "Layout not found: %@",
        .layoutsSectionTitle: "Layouts",
        .layoutsTabTitle: "Layouts",
        .matchReasonOnlyOpenWindow: "only open window for this app",
        .matchReasonSameLiveWindow: "same live window",
        .matchReasonSavedWindowIdentity: "saved window identity",
        .matchReasonWindowTitle: "window title",
        .matchedByLabel: "Matched by",
        .menuBarFooter: "When off, only the Perch icon is shown in the menu bar.",
        .menuBarSectionTitle: "Menu bar",
        .menuBarShowLabel: "Show label next to menu bar icon",
        .menuOutcomeAmbiguousWindows: "ambiguous windows",
        .menuOutcomeClosed: "closed",
        .menuOutcomeLaunchFailed: "launch failed",
        .menuOutcomeMoveFailed: "move failed",
        .menuOutcomeNotInstalled: "not installed",
        .menuOutcomeOpenedAndRestored: "opened and restored",
        .menuOutcomeRestored: "restored",
        .menuOutcomeSkipped: "skipped",
        .menuOutcomeWindowNotFound: "window not found",
        .newLayoutDefaultName: "New Layout",
        .newLayoutNamePlaceholder: "New layout name",
        .noLayouts: "No layouts yet.",
        .noLayoutsYet: "No layouts yet",
        .noRestoreShortcut: "No restore shortcut",
        .noWindowsSaved: "No windows saved",
        .noWindowsSavedYet: "No windows saved yet",
        .openMissingAppsDuringRestore: "Open missing apps during restore",
        .openSystemSettings: "Open System Settings",
        .openedDuringRestore: "Perch opened this app during restore.",
        .operationAlreadyRunning: "Another save or restore is already running.",
        .quitPerch: "Quit Perch",
        .reasonLabel: "Reason",
        .recordRestoreShortcutHelp: "Record restore shortcut",
        .refreshButton: "Refresh",
        .resetAccessibilityPermission: "Reset Accessibility Permission…",
        .resetPermissionButton: "Reset Permission",
        .restartPerch: "Restart Perch",
        .restoreLayoutFormat: "Restore %@",
        .restorePromptButton: "Restore",
        .restorePromptDismiss: "Dismiss restore suggestion",
        .restorePromptShortcutFormat: "Press %@ to restore",
        .restorePromptTitleFormat: "Restore %@?",
        .restoreSectionFooter: "When off, closed apps stay closed and only currently open windows are moved.",
        .restoreSectionTitle: "Restore",
        .saveButton: "Save",
        .saveCurrentWindowsFormat: "Save Current Windows to “%@”",
        .settingsMenuItem: "Settings…",
        .settingsWindowTitle: "Perch Settings",
        .shortcutAlreadyUsedRestoreFormat: "Shortcut is already used to restore %@.",
        .shortcutAlreadyUsedSaveFormat: "Shortcut is already used to save %@.",
        .shortcutRejectedTooltipFormat: "macOS rejected this shortcut with status %d. It may already be used by the system or another app.",
        .shortcutUnavailableTooltipFormat: "Shortcut %@ could not be registered. macOS or another app may already use it.",
        .slotNotFoundFormat: "Slot not found: %@",
        .someShortcutsUnavailable: "Some Shortcuts Are Unavailable",
        .startupSectionTitle: "Startup",
        .updateLayoutWindowsFormat: "Update “%@” with Current Windows",
        .updatesSectionTitle: "Updates",
        .windowLabel: "Window",
        .windowsAndShortcutFormat: "%d %@ · %@"
    ]
}
