import Foundation

enum LocalizationKey: String, CaseIterable, Sendable {
    case aboutAccessibilityLabel
    case aboutDescriptionPrivacy
    case aboutDescriptionRestore
    case aboutDescriptionSummary
    case aboutDiagnosticsRedacted
    case aboutExportDiagnostics
    case aboutGranted
    case aboutMadeBy
    case aboutMissing
    case aboutTabTitle
    case aboutVersionFormat
    case accessibilityBannerPendingMessage
    case accessibilityBannerPendingTitle
    case accessibilityBannerRequiredMessage
    case accessibilityBannerRequiredTitle
    case accessibilityGranted
    case accessibilityPermissionPending
    case accessibilityPermissionResetEnable
    case addButton
    case allWindowsRestored
    case appLabel
    case applicationClosed
    case applicationNotInstalled
    case autoRestoreAdvanced
    case autoRestoreAutomatic
    case autoRestoreDecisionAlreadyOffered
    case autoRestoreDecisionDisabled
    case autoRestoreDecisionEmptyLayout
    case autoRestoreDecisionError
    case autoRestoreDecisionNoLayout
    case autoRestoreDecisionPromptFormat
    case autoRestoreDecisionRestoreFormat
    case autoRestoreDecisionTopologyIncomplete
    case autoRestoreDecisionTopologyUnchanged
    case autoRestoreDoNothing
    case autoRestoreModeLabel
    case autoRestorePrompt
    case autoRestorePromptFooter
    case autoRestoreSectionTitle
    case autoRestoreSettleTimeoutFooter
    case autoRestoreSettleTimeoutLabel
    case automaticUpdateChecksToggle
    case bundleIDLabel
    case cancelButton
    case checkForUpdatesMenuItem
    case chooseLayoutName
    case clearCustomShortcutHelp
    case createLayout
    case createdLayoutFormat
    case deleteButton
    case deleteLayoutHelp
    case deleteLayoutMessageFormat
    case deleteLayoutTitle
    case diagnosticsExported
    case errorSectionTitle
    case generalTabTitle
    case grantAccessibilityPermission
    case grantAccessibilityPermissionPending
    case hotkeyActionRestoreFormat
    case hotkeyActionSaveFormat
    case hotkeyRecordPrompt
    case hotkeyRequiresModifier
    case languagePickerLabel
    case languageSectionTitle
    case lastAutomaticDecisionFormat
    case lastRestoreReport
    case launchAtLogin
    case launchAtLoginStatus
    case launchDidNotReturnApp
    case launchStatusDisabled
    case launchStatusEnabled
    case launchStatusRequiresApproval
    case launchStatusUnavailable
    case launchStatusUnknown
    case layoutNameCannotBeEmpty
    case layoutNameField
    case layoutNotFoundFormat
    case layoutsSectionTitle
    case layoutsTabTitle
    case matchReasonOnlyOpenWindow
    case matchReasonSameLiveWindow
    case matchReasonSavedWindowIdentity
    case matchReasonWindowTitle
    case matchedByLabel
    case menuBarFooter
    case menuBarSectionTitle
    case menuBarShowLabel
    case menuOutcomeAmbiguousWindows
    case menuOutcomeClosed
    case menuOutcomeLaunchFailed
    case menuOutcomeMoveFailed
    case menuOutcomeNotInstalled
    case menuOutcomeOpenedAndRestored
    case menuOutcomeRestored
    case menuOutcomeSkipped
    case menuOutcomeWindowNotFound
    case newLayoutDefaultName
    case newLayoutNamePlaceholder
    case noLayouts
    case noLayoutsYet
    case noRestoreShortcut
    case noWindowsSaved
    case noWindowsSavedYet
    case openMissingAppsDuringRestore
    case openSystemSettings
    case openedDuringRestore
    case operationAlreadyRunning
    case quitPerch
    case reasonLabel
    case recordRestoreShortcutHelp
    case refreshButton
    case resetAccessibilityPermission
    case resetPermissionButton
    case restartPerch
    case restoreLayoutFormat
    case restorePromptButton
    case restorePromptDismiss
    case restorePromptShortcutFormat
    case restorePromptTitleFormat
    case restoreSectionFooter
    case restoreSectionTitle
    case saveButton
    case saveCurrentWindowsFormat
    case settingsMenuItem
    case settingsWindowTitle
    case shortcutAlreadyUsedRestoreFormat
    case shortcutAlreadyUsedSaveFormat
    case shortcutRejectedTooltipFormat
    case shortcutUnavailableTooltipFormat
    case slotNotFoundFormat
    case someShortcutsUnavailable
    case startupSectionTitle
    case updateLayoutWindowsFormat
    case updatesSectionTitle
    case windowLabel
    case windowsAndShortcutFormat
}
