extension LocalizationCatalog {
    static let spanish: [LocalizationKey: String] = [
        .captureCurrentLayout: "Guardar disposición actual",
        .captureLayoutHelp: "Guarda las posiciones de las ventanas abiertas. Al actualizar una disposición se conserva la versión anterior.",
        .automaticLayoutTitle: "Disposición para las pantallas conectadas",
        .latestMatchingLayout: "Guardada más recientemente",
        .selectedAutomaticLayoutFormat: "Próxima restauración automática: %@",
        .noMatchingSavedLayout: "Guarda una disposición con estas pantallas para seleccionarla automáticamente.",
        .preferredForDisplays: "Preferida para estas pantallas",
        .useForAutomaticRestore: "Preferir para restauración automática",
        .followLatestSaved: "Volver a usar la guardada más recientemente",
        .lastSavedLabel: "Último guardado",
        .savedDisplaysFormat: "Pantallas: %d",
        .layoutDetails: "Detalles de la disposición",
        .layoutHistory: "Versiones guardadas",
        .noLayoutHistory: "Las versiones anteriores aparecerán aquí al actualizar o eliminar una disposición guardada.",
        .historyExplanation: "Se conservan en este Mac hasta 10 versiones por disposición, 100 en total. Recuperar una versión cambia la disposición guardada; no mueve ventanas.",
        .restoreVersion: "Recuperar esta versión",
        .historyRestored: "Versión recuperada. Puedes restaurar sus ventanas desde el menú de disposiciones.",
        .unknownDisplayArrangement: "Configuración de pantallas no guardada",
        .assignOpenWindow: "Asignar una ventana abierta…",
        .chooseOpenWindow: "Elige la ventana que corresponde a esta posición guardada. Su destino no cambia.",
        .windowReassigned: "Ventana asignada. Reintenta para moverla a la posición guardada.",
        .noOpenWindowsForApp: "Esta aplicación no tiene ventanas abiertas que se puedan mover. Abre la ventana deseada y actualiza.",
        .useThisWindow: "Usar esta ventana",
        .retryRemaining: "Reintentar ventanas restantes",
        .retryWindow: "Reintentar",
        .openAndRetry: "Abrir app y reintentar",
        .restoreActivity: "Progreso y resultado de restauración",
        .stopRestore: "Detener trabajo restante",
        .stoppingRestore: "Deteniendo… Se conservan los movimientos completados.",
        .waitingForDisplays: "Esperando a que se estabilicen las pantallas…",
        .workingOnApplicationFormat: "Restaurando ventanas: %@",
        .restoreProgressFormat: "Procesadas %d de %d ventanas",
        .undoLastRestore: "Deshacer última restauración",
        .undoExplanation: "Devuelve las ventanas a sus posiciones anteriores en las mismas pantallas. Omite las cerradas o sustituidas. Disponible hasta la próxima restauración o reinicio de la app.",
        .undoResults: "Resultado al deshacer",
        .outcomePending: "Pendiente",
        .outcomeCancelled: "Detenida",
        .noRestoreYet: "Restaura una disposición para ver aquí su progreso y resultado.",
        .reportHelp: "El reintento afecta solo a ventanas pendientes. Abrir una app aquí no cambia los ajustes automáticos ni recrea documentos o pestañas cerrados.",
        .closeButton: "Cerrar",
        .noWindowsToCapture: "No hay ventanas abiertas que se puedan mover. Abre las que quieras guardar y vuelve a intentarlo.",
        .layoutChangedSinceRestore: "La disposición ha cambiado. Restaura su versión actual antes de reintentar ventanas individuales.",
        .repairWindowUnavailable: "La ventana seleccionada ya no está disponible. Actualiza la lista y vuelve a elegir.",
        .nothingToUndo: "No hay movimientos de ventanas que deshacer.",
        .undoDisplayConfigurationChanged: "Reconecta la misma configuración de pantallas antes de deshacer los movimientos.",
        .windowAlreadyAssigned: "Esta ventana ya está asignada a otra posición de esta disposición.",
        .untitledWindow: "Ventana sin título",
        .storeRecoveryTitle: "Los diseños guardados requieren atención",
        .storeRecoveryMessage: "No se pudieron leer algunos diseños guardados. Perch conservó los archivos originales para recuperarlos. Guárdalos hasta restaurar una copia de seguridad válida o resolver el problema con soporte.",
        .storeRecoveryShowFiles: "Mostrar archivos conservados",
        .storeRecoveryDismiss: "Cerrar aviso",
        .applicationLaunchTimedOut: "La aplicación no terminó de iniciarse a tiempo. Puede abrirse más tarde; restaura el diseño de nuevo cuando esté lista.",
        .autoRestoreAutomaticFooter: "Tras desbloquear y estabilizar las pantallas, restaura sin confirmación la disposición preferida o la coincidente guardada más recientemente. Activa Iniciar al iniciar sesión para usarlo tras reiniciar.",
        .displaysChangedDuringSave: "Las pantallas cambiaron mientras se guardaba. Espera a que se estabilicen y vuelve a guardar el diseño.",
        .aboutAccessibilityLabel: "Accesibilidad",
        .aboutDescriptionPrivacy: "Los diseños permanecen en este Mac. Perch lee las ventanas al guardar y las mueve en restauraciones manuales o cuando está activada la restauración automática.",
        .aboutDescriptionRestore: "Crea diseños con nombre para trabajo, concentración, reuniones o cualquier otra cosa. Restáuralos desde la barra de menús o con atajos de teclado, incluso en varios monitores.",
        .aboutDescriptionSummary: "Perch es una app discreta de barra de menús para guardar la disposición de ventanas de tu Mac y restaurarla cuando necesites el mismo espacio de trabajo.",
        .aboutDiagnosticsRedacted: "El diagnóstico está redactado, no es anónimo. Incluye identificadores de apps y diseños, geometría de pantallas, recuentos, fechas, ajustes y datos del sistema. Excluye títulos de ventanas y nombres de diseños.",
        .aboutExportDiagnostics: "Exportar diagnóstico…",
        .aboutGranted: "Concedido",
        .aboutMadeBy: "Hecho por Code&live",
        .aboutMissing: "Falta",
        .aboutTabTitle: "Acerca de",
        .aboutVersionFormat: "Versión %@",
        .accessibilityBannerPendingMessage: "Si Perch ya está permitido en Ajustes del Sistema, reinícialo para que macOS asocie el permiso a la app en ejecución.",
        .accessibilityBannerPendingTitle: "Permiso de Accesibilidad pendiente",
        .accessibilityBannerRequiredMessage: "Perch necesita acceso de Accesibilidad para leer y mover ventanas.",
        .accessibilityBannerRequiredTitle: "Se requiere permiso de Accesibilidad",
        .accessibilityGranted: "Permiso de Accesibilidad concedido",
        .accessibilityPermissionPending: "Permiso de Accesibilidad pendiente. Reinicia Perch si ya está permitido.",
        .accessibilityPermissionResetEnable: "Permiso de Accesibilidad restablecido. Permite Perch en Ajustes del Sistema.",
        .addButton: "Añadir",
        .allWindowsRestored: "Todas las ventanas restauradas",
        .appLabel: "App",
        .applicationClosed: "La aplicación está cerrada.",
        .applicationNotInstalled: "La aplicación no está instalada.",
        .autoRestoreAdvanced: "Avanzado",
        .autoRestoreAutomatic: "Restaurar automáticamente",
        .autoRestoreDecisionAlreadyOffered: "sugerencia ya mostrada",
        .autoRestoreDecisionDisabled: "desactivado",
        .autoRestoreDecisionEmptyLayout: "el diseño coincidente está vacío",
        .autoRestoreDecisionError: "falló la decisión",
        .autoRestoreDecisionNoLayout: "no hay diseño para esta configuración",
        .autoRestoreDecisionPromptFormat: "se ofreció %@",
        .autoRestoreDecisionRestoreFormat: "restauración automática iniciada: %@",
        .autoRestoreDecisionTopologyIncomplete: "la configuración de pantallas aún está incompleta",
        .autoRestoreDecisionTopologyUnchanged: "la configuración de pantallas no cambió",
        .autoRestoreDoNothing: "No hacer nada",
        .autoRestoreModeLabel: "Al iniciar, despertar o cambiar las pantallas",
        .autoRestorePrompt: "Preguntarme",
        .autoRestorePromptFooter: "Perch ofrecerá restaurar el diseño guardado para esta configuración de pantallas.",
        .autoRestoreSectionTitle: "Restauración automática",
        .autoRestoreSettleTimeoutFooter: "Cuánto espera Perch a que el dock o las pantallas terminen de conectarse antes de comprobar la configuración.",
        .autoRestoreSettleTimeoutLabel: "Espera de estabilización",
        .automaticUpdateChecksToggle: "Buscar actualizaciones automáticamente",
        .bundleIDLabel: "Bundle ID",
        .cancelButton: "Cancelar",
        .checkForUpdatesMenuItem: "Buscar actualizaciones…",
        .chooseLayoutName: "Elige un nombre para este diseño.",
        .clearCustomShortcutHelp: "Borrar atajo personalizado",
        .createLayout: "Crear diseño",
        .createdLayoutFormat: "%@ creado",
        .deleteButton: "Eliminar",
        .deleteLayoutHelp: "Eliminar diseño",
        .deleteLayoutMessageFormat: "“%@” y sus ventanas guardadas se eliminarán.",
        .deleteLayoutTitle: "¿Eliminar diseño?",
        .diagnosticsExported: "Diagnóstico exportado",
        .errorSectionTitle: "Error",
        .generalTabTitle: "General",
        .grantAccessibilityPermission: "Conceder permiso de Accesibilidad…",
        .grantAccessibilityPermissionPending: "Permiso de Accesibilidad pendiente…",
        .hotkeyActionRestoreFormat: "restaurar %@",
        .hotkeyActionSaveFormat: "guardar %@",
        .hotkeyRecordPrompt: "Haz clic aquí y pulsa un atajo",
        .hotkeyRequiresModifier: "Usa al menos un modificador",
        .languagePickerLabel: "Idioma",
        .languageSectionTitle: "Idioma",
        .lastAutomaticDecisionFormat: "Restauración automática: %@",
        .lastRestoreReport: "Último informe de restauración",
        .launchAtLogin: "Abrir al iniciar sesión",
        .launchAtLoginStatus: "Estado del inicio de sesión",
        .launchDidNotReturnApp: "macOS no devolvió una aplicación en ejecución.",
        .launchStatusDisabled: "Desactivado",
        .launchStatusEnabled: "Activado",
        .launchStatusRequiresApproval: "Requiere aprobación en Ajustes del Sistema",
        .launchStatusUnavailable: "No disponible",
        .launchStatusUnknown: "Desconocido",
        .layoutNameCannotBeEmpty: "El nombre del diseño no puede estar vacío.",
        .layoutNameField: "Nombre del diseño",
        .layoutNotFoundFormat: "Diseño no encontrado: %@",
        .layoutsSectionTitle: "Diseños",
        .layoutsTabTitle: "Diseños",
        .matchReasonOnlyOpenWindow: "única ventana abierta de esta app",
        .matchReasonSameLiveWindow: "misma ventana activa",
        .matchReasonSavedWindowIdentity: "identidad de ventana guardada",
        .matchReasonWindowTitle: "título de la ventana",
        .matchedByLabel: "Coincidencia por",
        .menuBarFooter: "Si está desactivado, solo se muestra el icono de Perch en la barra de menús.",
        .menuBarSectionTitle: "Barra de menús",
        .menuBarShowLabel: "Mostrar etiqueta junto al icono de la barra",
        .menuOutcomeAmbiguousWindows: "ventanas ambiguas",
        .menuOutcomeClosed: "cerrada",
        .menuOutcomeLaunchFailed: "fallo al abrir",
        .menuOutcomeMoveFailed: "fallo al mover",
        .menuOutcomeNotInstalled: "no instalada",
        .menuOutcomeOpenedAndRestored: "abierta y restaurada",
        .menuOutcomeRestored: "restaurada",
        .menuOutcomeSkipped: "omitida",
        .menuOutcomeWindowNotFound: "ventana no encontrada",
        .newLayoutDefaultName: "Nuevo diseño",
        .newLayoutNamePlaceholder: "Nombre del nuevo diseño",
        .noLayouts: "Todavía no hay diseños.",
        .noLayoutsYet: "Todavía no hay diseños",
        .noRestoreShortcut: "Sin atajo de restauración",
        .noWindowsSaved: "No hay ventanas guardadas",
        .noWindowsSavedYet: "Todavía no hay ventanas guardadas",
        .openMissingAppsDuringRestore: "Abrir apps faltantes al restaurar",
        .openSystemSettings: "Abrir Ajustes del Sistema",
        .openedDuringRestore: "Perch abrió esta app durante la restauración.",
        .operationAlreadyRunning: "Ya se está ejecutando otra operación de guardado o restauración.",
        .quitPerch: "Salir de Perch",
        .reasonLabel: "Motivo",
        .recordRestoreShortcutHelp: "Grabar atajo de restauración",
        .refreshButton: "Actualizar",
        .resetAccessibilityPermission: "Restablecer permiso de Accesibilidad…",
        .resetPermissionButton: "Restablecer permiso",
        .restartPerch: "Reiniciar Perch",
        .restoreLayoutFormat: "Restaurar %@",
        .restorePromptButton: "Restaurar",
        .restorePromptDismiss: "Cerrar sugerencia de restauración",
        .restorePromptShortcutFormat: "Pulsa %@ para restaurar",
        .restorePromptTitleFormat: "¿Restaurar %@?",
        .restoreSectionFooter: "Si está desactivado, las apps cerradas permanecen cerradas y solo se mueven las ventanas abiertas.",
        .restoreSectionTitle: "Restauración",
        .saveButton: "Guardar",
        .saveCurrentWindowsFormat: "Guardar ventanas actuales en “%@”",
        .settingsMenuItem: "Ajustes…",
        .settingsWindowTitle: "Ajustes de Perch",
        .shortcutAlreadyUsedRestoreFormat: "El atajo ya se usa para restaurar %@.",
        .shortcutAlreadyUsedSaveFormat: "El atajo ya se usa para guardar %@.",
        .shortcutRejectedTooltipFormat: "macOS rechazó este atajo con estado %d. Puede que el sistema u otra app ya lo use.",
        .shortcutUnavailableTooltipFormat: "No se pudo registrar el atajo %@. Puede que macOS u otra app ya lo use.",
        .slotNotFoundFormat: "Slot no encontrado: %@",
        .someShortcutsUnavailable: "Algunos atajos no están disponibles",
        .startupSectionTitle: "Inicio",
        .updateLayoutWindowsFormat: "Actualizar “%@” con las ventanas actuales",
        .updatesSectionTitle: "Actualizaciones",
        .windowLabel: "Ventana",
        .windowsAndShortcutFormat: "%d %@ · %@"
    ]
}
