extension LocalizationCatalog {
    static let czech: [LocalizationKey: String] = [
        .storeRecoveryTitle: "Uložená rozložení vyžadují pozornost",
        .storeRecoveryMessage: "Některá uložená rozložení nešla načíst. Perch zachoval původní soubory pro obnovu. Ponechte je, dokud neobnovíte platnou zálohu nebo problém nevyřešíte s podporou.",
        .storeRecoveryShowFiles: "Ukázat zachované soubory",
        .storeRecoveryDismiss: "Zavřít upozornění",
        .applicationLaunchTimedOut: "Aplikace se nestihla spustit. Může se otevřít později; až bude připravená, zkuste rozložení obnovit znovu.",
        .autoRestoreAutomaticFooter: "Obnoví naposledy uložené rozložení pro připojené displeje. Pokud už používáte klávesnici nebo myš, Perch se nejprve zeptá. Pro obnovu po restartu zapněte Spouštět při přihlášení.",
        .displaysChangedDuringSave: "Během ukládání se změnily displeje. Počkejte na jejich ustálení a uložte rozložení znovu.",
        .aboutAccessibilityLabel: "Zpřístupnění",
        .aboutDescriptionPrivacy: "Rozložení zůstávají na tomto Macu. Perch čte okna při ukládání a přesouvá je při ručním obnovení nebo když je zapnuté automatické obnovení.",
        .aboutDescriptionRestore: "Vytvářejte pojmenovaná rozložení pro práci, soustředění, schůzky nebo cokoliv dalšího. Obnovíte je z lišty nebo klávesovou zkratkou, i přes více displejů.",
        .aboutDescriptionSummary: "Perch je nenápadná aplikace v liště pro ukládání rozložení oken na Macu a jeho obnovení, když znovu potřebujete stejný pracovní prostor.",
        .aboutDiagnosticsRedacted: "Diagnostika je redigovaná, nikoli anonymní. Obsahuje identifikátory aplikací a rozložení, geometrii displejů, počty, časové údaje, nastavení a údaje o systému. Názvy oken a rozložení se neexportují.",
        .aboutExportDiagnostics: "Exportovat diagnostiku…",
        .aboutGranted: "Povoleno",
        .aboutMadeBy: "Vytvořilo Code&live",
        .aboutMissing: "Chybí",
        .aboutTabTitle: "O aplikaci",
        .aboutVersionFormat: "Verze %@",
        .accessibilityBannerPendingMessage: "Pokud už je Perch v Nastavení systému povolený, restartujte ho, aby macOS oprávnění připojil k běžící aplikaci.",
        .accessibilityBannerPendingTitle: "Oprávnění Zpřístupnění čeká",
        .accessibilityBannerRequiredMessage: "Perch potřebuje přístup ke Zpřístupnění, aby mohl číst a přesouvat okna.",
        .accessibilityBannerRequiredTitle: "Je vyžadováno oprávnění Zpřístupnění",
        .accessibilityGranted: "Oprávnění Zpřístupnění povoleno",
        .accessibilityPermissionPending: "Oprávnění Zpřístupnění čeká. Pokud už je Perch povolený, restartujte ho.",
        .accessibilityPermissionResetEnable: "Oprávnění Zpřístupnění resetováno. Povolte Perch v Nastavení systému.",
        .addButton: "Přidat",
        .allWindowsRestored: "Všechna okna obnovena",
        .appLabel: "Aplikace",
        .applicationClosed: "Aplikace je zavřená.",
        .applicationNotInstalled: "Aplikace není nainstalovaná.",
        .autoRestoreAdvanced: "Pokročilé",
        .autoRestoreAutomatic: "Obnovit automaticky",
        .autoRestoreDecisionAlreadyOffered: "nabídka už byla zobrazena",
        .autoRestoreDecisionDisabled: "vypnuto",
        .autoRestoreDecisionEmptyLayout: "odpovídající rozložení je prázdné",
        .autoRestoreDecisionError: "rozhodnutí selhalo",
        .autoRestoreDecisionNoLayout: "pro tuto sestavu není rozložení",
        .autoRestoreDecisionPromptFormat: "nabídnuto %@",
        .autoRestoreDecisionRestoreFormat: "zahájena automatická obnova: %@",
        .autoRestoreDecisionTopologyIncomplete: "sestava displejů ještě není kompletní",
        .autoRestoreDecisionTopologyUnchanged: "sestava displejů se nezměnila",
        .autoRestoreDoNothing: "Nedělat nic",
        .autoRestoreModeLabel: "Při spuštění, probuzení nebo změně displejů",
        .autoRestorePrompt: "Zeptat se",
        .autoRestorePromptFooter: "Perch nabídne obnovení rozložení uloženého pro tuto sestavu displejů.",
        .autoRestoreSectionTitle: "Automatické obnovení",
        .autoRestoreSettleTimeoutFooter: "Jak dlouho Perch čeká, než se dok nebo displeje dokončí připojování, a teprve potom zkontroluje sestavu.",
        .autoRestoreSettleTimeoutLabel: "Čas na ustálení displejů",
        .automaticUpdateChecksToggle: "Automaticky kontrolovat aktualizace",
        .bundleIDLabel: "Bundle ID",
        .cancelButton: "Zrušit",
        .checkForUpdatesMenuItem: "Zkontrolovat aktualizace…",
        .chooseLayoutName: "Zvolte název tohoto rozložení.",
        .clearCustomShortcutHelp: "Vymazat vlastní zkratku",
        .createLayout: "Vytvořit rozložení",
        .createdLayoutFormat: "Vytvořeno %@",
        .deleteButton: "Smazat",
        .deleteLayoutHelp: "Smazat rozložení",
        .deleteLayoutMessageFormat: "„%@“ a jeho uložená okna budou odstraněna.",
        .deleteLayoutTitle: "Smazat rozložení?",
        .diagnosticsExported: "Diagnostika exportována",
        .errorSectionTitle: "Chyba",
        .generalTabTitle: "Obecné",
        .grantAccessibilityPermission: "Udělit oprávnění Zpřístupnění…",
        .grantAccessibilityPermissionPending: "Oprávnění Zpřístupnění čeká…",
        .hotkeyActionRestoreFormat: "obnovit %@",
        .hotkeyActionSaveFormat: "uložit %@",
        .hotkeyRecordPrompt: "Klikněte sem a stiskněte zkratku",
        .hotkeyRequiresModifier: "Použijte alespoň jeden modifikátor",
        .languagePickerLabel: "Jazyk",
        .languageSectionTitle: "Jazyk",
        .lastAutomaticDecisionFormat: "Automatické obnovení: %@",
        .lastRestoreReport: "Poslední hlášení obnovení",
        .launchAtLogin: "Spustit po přihlášení",
        .launchAtLoginStatus: "Stav položky přihlášení",
        .launchDidNotReturnApp: "macOS nevrátil běžící aplikaci.",
        .launchStatusDisabled: "Vypnuto",
        .launchStatusEnabled: "Zapnuto",
        .launchStatusRequiresApproval: "Vyžaduje schválení v Nastavení systému",
        .launchStatusUnavailable: "Nedostupné",
        .launchStatusUnknown: "Neznámé",
        .layoutNameCannotBeEmpty: "Název rozložení nesmí být prázdný.",
        .layoutNameField: "Název rozložení",
        .layoutNotFoundFormat: "Rozložení nenalezeno: %@",
        .layoutsSectionTitle: "Rozložení",
        .layoutsTabTitle: "Rozložení",
        .matchReasonOnlyOpenWindow: "jediné otevřené okno této aplikace",
        .matchReasonSameLiveWindow: "stejné živé okno",
        .matchReasonSavedWindowIdentity: "uložená identita okna",
        .matchReasonWindowTitle: "titulek okna",
        .matchedByLabel: "Shoda podle",
        .menuBarFooter: "Když je volba vypnutá, v liště se zobrazí jen ikona Perch.",
        .menuBarSectionTitle: "Lišta nabídek",
        .menuBarShowLabel: "Zobrazit popisek vedle ikony v liště",
        .menuOutcomeAmbiguousWindows: "nejednoznačná okna",
        .menuOutcomeClosed: "zavřeno",
        .menuOutcomeLaunchFailed: "spuštění selhalo",
        .menuOutcomeMoveFailed: "přesun selhal",
        .menuOutcomeNotInstalled: "není nainstalováno",
        .menuOutcomeOpenedAndRestored: "otevřeno a obnoveno",
        .menuOutcomeRestored: "obnoveno",
        .menuOutcomeSkipped: "přeskočeno",
        .menuOutcomeWindowNotFound: "okno nenalezeno",
        .newLayoutDefaultName: "Nové rozložení",
        .newLayoutNamePlaceholder: "Název nového rozložení",
        .noLayouts: "Zatím žádná rozložení.",
        .noLayoutsYet: "Zatím žádná rozložení",
        .noRestoreShortcut: "Žádná zkratka pro obnovení",
        .noWindowsSaved: "Nejsou uložena žádná okna",
        .noWindowsSavedYet: "Zatím nejsou uložena žádná okna",
        .openMissingAppsDuringRestore: "Při obnovení otevřít chybějící aplikace",
        .openSystemSettings: "Otevřít Nastavení systému",
        .openedDuringRestore: "Perch tuto aplikaci během obnovení otevřel.",
        .operationAlreadyRunning: "Jiné ukládání nebo obnovování právě běží.",
        .quitPerch: "Ukončit Perch",
        .reasonLabel: "Důvod",
        .recordRestoreShortcutHelp: "Nahrát zkratku pro obnovení",
        .refreshButton: "Obnovit",
        .resetAccessibilityPermission: "Resetovat oprávnění Zpřístupnění…",
        .resetPermissionButton: "Resetovat oprávnění",
        .restartPerch: "Restartovat Perch",
        .restoreLayoutFormat: "Obnovit %@",
        .restorePromptButton: "Obnovit",
        .restorePromptDismiss: "Zavřít nabídku obnovení",
        .restorePromptShortcutFormat: "Obnovíte stisknutím %@",
        .restorePromptTitleFormat: "Obnovit %@?",
        .restoreSectionFooter: "Když je volba vypnutá, zavřené aplikace zůstanou zavřené a přesunou se jen právě otevřená okna.",
        .restoreSectionTitle: "Obnovení",
        .saveButton: "Uložit",
        .saveCurrentWindowsFormat: "Uložit aktuální okna do „%@“",
        .settingsMenuItem: "Nastavení…",
        .settingsWindowTitle: "Nastavení Perch",
        .shortcutAlreadyUsedRestoreFormat: "Zkratka se už používá pro obnovení %@.",
        .shortcutAlreadyUsedSaveFormat: "Zkratka se už používá pro uložení %@.",
        .shortcutRejectedTooltipFormat: "macOS odmítl tuto zkratku se stavem %d. Možná ji už používá systém nebo jiná aplikace.",
        .shortcutUnavailableTooltipFormat: "Zkratku %@ se nepodařilo zaregistrovat. Možná ji už používá macOS nebo jiná aplikace.",
        .slotNotFoundFormat: "Slot nenalezen: %@",
        .someShortcutsUnavailable: "Některé zkratky nejsou dostupné",
        .startupSectionTitle: "Spuštění",
        .updateLayoutWindowsFormat: "Aktualizovat „%@“ aktuálními okny",
        .updatesSectionTitle: "Aktualizace",
        .windowLabel: "Okno",
        .windowsAndShortcutFormat: "%d %@ · %@"
    ]
}
